const test=require('node:test');
const assert=require('node:assert/strict');
process.env.DB_PATH=':memory:';
const {db}=require('../src/db');
const cat=require('../src/services/finanzas/catalogos');
const motor=require('../src/services/finanzas/motor');
const caja=require('../src/services/caja');
const admin=Number(db.prepare("INSERT INTO usuarios(nombre,email,password_hash,rol_id)VALUES('Caja','caja-finanzas@test','x',1)").run().lastInsertRowid);
function base(codigo){const e=cat.crearEntidadFundacion({codigo,nombre:codigo,tipo:'empresa',fechaInicial:'2026-07-01',usuarioId:admin}).entidad;const pc=db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo='1101'").get(e.id).id;const bolsillo=db.prepare("SELECT id FROM fin_bolsillos WHERE entidad_id=? AND tipo='sin_asignar'").get(e.id).id;const c1=cat.crearCuentaFinanciera({entidadId:e.id,cuentaContableId:pc,codigo:'CAJA1',nombre:'Caja 1',tipo:'caja',usuarioId:admin});const c2=cat.crearCuentaFinanciera({entidadId:e.id,cuentaContableId:pc,codigo:'CAJA2',nombre:'Caja 2',tipo:'caja',usuarioId:admin});const caja1=Number(db.prepare('INSERT INTO cajas(nombre,entidad_id,cuenta_financiera_id)VALUES(?,?,?)').run('Fisica 1',e.id,c1.id).lastInsertRowid);const caja2=Number(db.prepare('INSERT INTO cajas(nombre,entidad_id,cuenta_financiera_id)VALUES(?,?,?)').run('Fisica 2',e.id,c2.id).lastInsertRowid);return{e,bolsillo,c1,c2,caja1,caja2}}
test('caja sin asociación rechaza operaciones y una cuenta ajena no puede asociarse',()=>{const x=base('CAJA_A');const sin=Number(db.prepare('INSERT INTO cajas(nombre)VALUES(?)').run('Sin configurar').lastInsertRowid);assert.throws(()=>caja.abrirTurno({cajaId:sin,usuarioId:admin}),/configuración financiera/);const y=base('CAJA_B');assert.throws(()=>db.prepare('INSERT INTO cajas(nombre,entidad_id,cuenta_financiera_id)VALUES(?,?,?)').run('Cruce',x.e.id,y.c1.id),/caja activa de la entidad/)});
test('apertura no crea dinero; manuales, transferencia, arqueo y cierre usan el motor',()=>{const x=base('CAJA_C');const t1=caja.abrirTurno({cajaId:x.caja1,usuarioId:admin});assert.equal(motor.eventos(x.e.id).length,0);caja.registrarManual({turnoId:t1,tipo:'ingreso',monto:20,motivo:'fondo',usuarioId:admin,fechaEfectiva:'2026-07-01',clave:'ingreso-caja'});assert.equal(motor.saldo(x.c1.id,x.bolsillo).tes,2000);const t2=caja.abrirTurno({cajaId:x.caja2,usuarioId:admin});caja.transferirEntreCajas({cajaOrigenId:x.caja1,cajaDestinoId:x.caja2,monto:5,usuarioId:admin,fechaEfectiva:'2026-07-01',clave:'trans-caja'});assert.equal(motor.saldo(x.c2.id,x.bolsillo).tes,500);const cierre=caja.cerrarTurno({turnoId:t2,montoContado:6,notas:'sobrante',usuarioId:admin,clave:'arqueo-caja'});assert.equal(cierre.diferencia,6);assert.equal(db.prepare("SELECT COUNT(*) n FROM fin_eventos_financieros WHERE tipo='ajuste_conciliacion'").get().n,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM movimientos_caja').get().n,0);});
test('cobro de venta crea un evento idempotente sin movimiento histórico',()=>{const x=base('CAJA_D');const turno=caja.abrirTurno({cajaId:x.caja1,usuarioId:admin});const primero=caja.registrarCobroVenta({turnoId:turno,ventaId:9,pagoId:99,monto:12,metodoPago:'Efectivo',usuarioId:admin,fechaEfectiva:'2026-07-01'});const segundo=caja.registrarCobroVenta({turnoId:turno,ventaId:9,pagoId:99,monto:12,metodoPago:'Efectivo',usuarioId:admin,fechaEfectiva:'2026-07-01'});assert.equal(primero.id,segundo.id);assert.equal(motor.saldo(x.c1.id,x.bolsillo).tes,1200);assert.equal(db.prepare('SELECT COUNT(*) n FROM movimientos_caja').get().n,0);assert.ok(db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo='2199'").get(x.e.id));});
test('la asociación exige una caja activa propia; conserva el historial y revierte fallos',()=>{const x=base('CAJA_E');const plan=db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo='1101'").get(x.e.id);const banco=cat.crearCuentaFinanciera({entidadId:x.e.id,cuentaContableId:plan.id,codigo:'BANCO',nombre:'Banco',tipo:'banco',usuarioId:admin});assert.throws(()=>db.prepare('INSERT INTO cajas(nombre,entidad_id,cuenta_financiera_id)VALUES(?,?,?)').run('No caja',x.e.id,banco.id),/caja activa/);const turno=caja.abrirTurno({cajaId:x.caja1,usuarioId:admin});db.prepare("INSERT INTO movimientos_caja(turno_id,tipo,metodo_pago,monto,motivo,usuario_id)VALUES(?,?,?,?,?,?)").run(turno,'historico','Efectivo',7,'legado',admin);db.exec("CREATE TRIGGER fallo_caja BEFORE INSERT ON fin_asignaciones_bolsillo BEGIN SELECT RAISE(ABORT,'fallo caja'); END");assert.throws(()=>caja.registrarManual({turnoId:turno,tipo:'ingreso',monto:3,motivo:'fallo',usuarioId:admin,clave:'fallo-caja'}),/fallo caja/);db.exec('DROP TRIGGER fallo_caja');assert.equal(db.prepare('SELECT COUNT(*) n FROM movimientos_caja').get().n,1);assert.equal(motor.eventos(x.e.id).length,0);db.prepare("UPDATE fin_periodos SET estado='cerrado' WHERE entidad_id=?").run(x.e.id);assert.throws(()=>caja.registrarManual({turnoId:turno,tipo:'ingreso',monto:3,motivo:'cerrado',usuarioId:admin,clave:'cerrado-caja'}),/período financiero no está abierto/);});
test('configurar caja valida acceso, cuenta y deja auditoría',()=>{const x=base('CAJA_F');const plan=db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo='1101'").get(x.e.id);const libre=cat.crearCuentaFinanciera({entidadId:x.e.id,cuentaContableId:plan.id,codigo:'LIBRE',nombre:'Caja libre',tipo:'caja',usuarioId:admin});const pendiente=Number(db.prepare('INSERT INTO cajas(nombre)VALUES(?)').run('Pendiente').lastInsertRowid);const configurada=caja.configurarCaja({cajaId:pendiente,entidadId:x.e.id,cuentaFinancieraId:libre.id,usuarioId:admin});assert.equal(configurada.cuenta_financiera_id,libre.id);assert.equal(db.prepare("SELECT COUNT(*) n FROM fin_auditoria WHERE entidad_tabla='cajas' AND entidad_registro_id=?").get(pendiente).n,1);assert.throws(()=>caja.configurarCaja({cajaId:pendiente,entidadId:x.e.id,cuentaFinancieraId:x.c2.id,usuarioId:admin}),/ya está asociada|Recurso/);});
