import { useEffect, useState } from "react";
import { Alert, Box, Button, MenuItem, Stack, TextField } from "@mui/material";
import FormDialog from "../FormDialog";
import { listarBolsillos, listarCajas, listarEntidadesFinancieras, transferirEntreCajas } from "../../api/endpoints";
import { useNotify } from "../../hooks/useNotify";
import { fechaHoyISO } from "../../utils/format";

export default function TransferenciasCajaTab() {
  const notify = useNotify(); const [entidades, setEntidades] = useState([]); const [cajas, setCajas] = useState([]); const [bolsillos, setBolsillos] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ entidad: "", origen: "", destino: "", bolsilloOrigen: "", bolsilloDestino: "", monto: "", fecha: fechaHoyISO() });
  useEffect(() => { Promise.all([listarEntidadesFinancieras(), listarCajas()]).then(([e, c]) => { setEntidades(e); setCajas(c); }).catch(notify.error); }, [notify]);
  const cambiarEntidad = async (id) => { setForm((f) => ({ ...f, entidad: id, origen: "", destino: "" })); try { setBolsillos(await listarBolsillos(id)); } catch (e) { notify.error(e); } };
  const disponibles = cajas.filter((c) => String(c.entidad_id) === String(form.entidad) && c.cuenta_financiera_id);
  const enviar = async () => { if (!form.origen || !form.destino || !form.monto || form.origen === form.destino) return notify.error("Selecciona cajas distintas e ingresa un monto."); try { await transferirEntreCajas({ caja_origen_id: form.origen, caja_destino_id: form.destino, bolsillo_origen_id: form.bolsilloOrigen || undefined, bolsillo_destino_id: form.bolsilloDestino || undefined, monto: Number(form.monto), fecha: form.fecha }); notify.success("Transferencia registrada"); setOpen(false); } catch (e) { notify.error(e); } };
  if (!entidades.length) return <Alert severity="info">No tienes acceso financiero para transferir entre cajas.</Alert>;
  return <Box><Button variant="contained" onClick={() => setOpen(true)}>Nueva transferencia</Button><FormDialog open={open} onClose={() => setOpen(false)} title="Transferencias entre cajas"><Stack spacing={2}><TextField select label="Entidad" value={form.entidad} onChange={(e) => cambiarEntidad(e.target.value)}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField><TextField select label="Caja origen" value={form.origen} onChange={(e) => setForm((f) => ({ ...f, origen: e.target.value }))}>{disponibles.map((c) => <MenuItem key={c.id} value={c.id}>{c.nombre}</MenuItem>)}</TextField><TextField select label="Caja destino" value={form.destino} onChange={(e) => setForm((f) => ({ ...f, destino: e.target.value }))}>{disponibles.filter((c) => String(c.id) !== String(form.origen)).map((c) => <MenuItem key={c.id} value={c.id}>{c.nombre}</MenuItem>)}</TextField><TextField label="Monto" type="number" value={form.monto} onChange={(e) => setForm((f) => ({ ...f, monto: e.target.value }))} /><TextField label="Fecha" type="date" InputLabelProps={{ shrink: true }} value={form.fecha} onChange={(e) => setForm((f) => ({ ...f, fecha: e.target.value }))} /><Button variant="contained" onClick={enviar}>Transferir</Button></Stack></FormDialog></Box>;
}
