import { useCallback, useEffect, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Box, Button, Grid, MenuItem, Stack, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import DataTable from "../DataTable";
import FormDialog from "../FormDialog";
import { useNotify } from "../../hooks/useNotify";
import { formatoFecha, formatoMoneda } from "../../utils/format";
import { listarBolsillos, listarCuentasFinancieras, listarEntidadesFinancieras, listarMovimientosManuales, registrarMovimientoManual } from "../../api/endpoints";

const hoy = () => new Date().toISOString().slice(0, 10);
const schema = z.object({ entidad_id: z.string().min(1, "Elige una entidad"), cuenta_financiera_id: z.string().min(1, "Elige una cuenta"), bolsillo_id: z.string().optional(), tipo: z.enum(["ingreso", "egreso"]), monto: z.string().regex(/^\d+(\.\d+)?$/, "Ingresa un monto válido"), motivo: z.string().trim().min(1, "El motivo es obligatorio"), fecha: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) });
const valoresIniciales = () => ({ entidad_id: "", cuenta_financiera_id: "", bolsillo_id: "", tipo: "ingreso", monto: "", motivo: "", fecha: hoy() });
const clave = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;

export default function MovimientosManualesTab() {
  const notify = useNotify(); const [entidades, setEntidades] = useState([]); const [cuentas, setCuentas] = useState([]); const [bolsillos, setBolsillos] = useState([]); const [movimientos, setMovimientos] = useState([]); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const { register, handleSubmit, reset, setValue, watch, formState: { errors } } = useForm({ resolver: zodResolver(schema), defaultValues: valoresIniciales() });
  const entidadId = watch("entidad_id");
  const cargar = useCallback(async (id = entidadId) => { if (!id) { setMovimientos([]); return; } try { setMovimientos(await listarMovimientosManuales(id)); } catch (error) { notify.error(error); } }, [entidadId, notify]);
  useEffect(() => { listarEntidadesFinancieras().then((rows) => setEntidades(rows)).catch(notify.error); }, [notify]);
  useEffect(() => { cargar(); }, [cargar]);
  const cambiarEntidad = async (id) => { setValue("entidad_id", id); setValue("cuenta_financiera_id", ""); setValue("bolsillo_id", ""); if (!id) { setCuentas([]); setBolsillos([]); return; } try { const [cs, bs] = await Promise.all([listarCuentasFinancieras(id), listarBolsillos(id)]); setCuentas(cs.filter((x) => x.estado === "activa")); setBolsillos(bs.filter((x) => x.estado === "activa")); } catch (error) { notify.error(error); } };
  const abrir = () => { reset({ ...valoresIniciales(), entidad_id: entidadId || "" }); if (entidadId) cambiarEntidad(entidadId); setOpen(true); };
  const guardar = async (form) => { setSaving(true); try { await registrarMovimientoManual(form.entidad_id, { tipo: form.tipo, cuenta_financiera_id: Number(form.cuenta_financiera_id), bolsillo_id: form.bolsillo_id ? Number(form.bolsillo_id) : undefined, monto: form.monto, motivo: form.motivo, fecha: form.fecha }, clave()); notify.success("Movimiento financiero registrado."); setOpen(false); await cargar(form.entidad_id); } catch (error) { notify.error(error); } finally { setSaving(false); } };
  return <Box><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ sm: "center" }} sx={{ mb: 2 }}><Typography color="text.secondary">Registra ingresos y egresos en cualquier cuenta financiera, sin requerir un turno de caja.</Typography><Button variant="contained" startIcon={<AddIcon />} onClick={abrir}>Nuevo movimiento</Button></Stack><TextField select size="small" label="Entidad económica" value={entidadId || ""} onChange={(e) => cambiarEntidad(e.target.value)} sx={{ minWidth: 280, mb: 2 }}><MenuItem value="">Selecciona una entidad</MenuItem>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField><DataTable rows={movimientos} defaultOrderBy="evento_financiero_id" defaultOrder="desc" columns={[{ field: "fecha", headerName: "Fecha", renderCell: (r) => formatoFecha(r.fecha) }, { field: "tipo", headerName: "Tipo", renderCell: (r) => r.tipo === "ingreso_manual" ? "Ingreso" : "Egreso" }, { field: "cuenta_nombre", headerName: "Cuenta" }, { field: "bolsillo_nombre", headerName: "Bolsillo", renderCell: (r) => r.bolsillo_nombre || "Sin asignar" }, { field: "motivo", headerName: "Motivo", minWidth: 240 }, { field: "importe", headerName: "Importe", align: "right", renderCell: (r) => formatoMoneda(r.importe) }]} />
    <FormDialog open={open} onClose={() => setOpen(false)} title="Movimiento manual financiero"><Box component="form" onSubmit={handleSubmit(guardar)}><Grid container spacing={2}><Grid item xs={12}><TextField select fullWidth required label="Entidad económica" value={watch("entidad_id")} error={!!errors.entidad_id} helperText={errors.entidad_id?.message} onChange={(e) => cambiarEntidad(e.target.value)}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField select fullWidth required label="Tipo" value={watch("tipo")} onChange={(e) => setValue("tipo", e.target.value)}><MenuItem value="ingreso">Ingreso</MenuItem><MenuItem value="egreso">Egreso</MenuItem></TextField></Grid><Grid item xs={12} sm={6}><TextField fullWidth required type="date" label="Fecha" InputLabelProps={{ shrink: true }} {...register("fecha")} error={!!errors.fecha} helperText={errors.fecha?.message} /></Grid><Grid item xs={12}><TextField select fullWidth required label="Cuenta financiera" value={watch("cuenta_financiera_id")} error={!!errors.cuenta_financiera_id} helperText={errors.cuenta_financiera_id?.message} onChange={(e) => setValue("cuenta_financiera_id", e.target.value)}>{cuentas.map((c) => <MenuItem key={c.id} value={c.id}>{c.nombre} ({c.tipo})</MenuItem>)}</TextField></Grid><Grid item xs={12}><TextField select fullWidth label="Bolsillo (opcional)" value={watch("bolsillo_id")} onChange={(e) => setValue("bolsillo_id", e.target.value)}><MenuItem value="">Sin asignar</MenuItem>{bolsillos.map((b) => <MenuItem key={b.id} value={b.id}>{b.nombre}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField fullWidth required type="number" inputProps={{ min: 0.01, step: "0.01" }} label="Monto (S/)" {...register("monto")} error={!!errors.monto} helperText={errors.monto?.message} /></Grid><Grid item xs={12} sm={6}><TextField fullWidth required label="Motivo" {...register("motivo")} error={!!errors.motivo} helperText={errors.motivo?.message} /></Grid></Grid><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 3 }}><Button onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" variant="contained" disabled={saving}>{saving ? "Registrando…" : "Registrar"}</Button></Stack></Box></FormDialog></Box>;
}
