import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Chip, CircularProgress, Divider, FormControlLabel, MenuItem, Paper, Stack, Switch, TextField, Typography } from '@mui/material';
import { Link as RouterLink } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import EmptyState from '../components/EmptyState';
import { useAuth } from '../context/AuthContext';
import { useNotify } from '../hooks/useNotify';
import { cambiarEstadoAlertaFinanciera, configuracionAlertasFinancieras, guardarConfiguracionAlertasFinancieras, historialAlertaFinanciera, listarAlertasFinancieras, listarEntidadesFinancieras } from '../api/endpoints';

const tonos = { critica: 'error', advertencia: 'warning', informativa: 'info' };
const etiquetas = { activa: 'Activa', leida: 'Leída', resuelta: 'Resuelta', ignorada: 'Ignorada' };
const dineroTipos = new Set(['bolsillo_bajo_minimo', 'dinero_sin_asignar']);
const diasTipos = new Set(['meta_proxima_vencer', 'politica_sin_aplicaciones']);

export default function AlertasFinancierasPage() {
  const notify = useNotify(); const { hasRole } = useAuth();
  const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState(''); const [alertas, setAlertas] = useState([]); const [config, setConfig] = useState([]);
  const [filtros, setFiltros] = useState({ estado: '', tipo: '', severidad: '' }); const [historial, setHistorial] = useState({}); const [cargando, setCargando] = useState(true); const [error, setError] = useState(''); const [guardando, setGuardando] = useState(false);
  const entidad = entidades.find((x) => String(x.id) === String(entidadId)); const puedeConfigurar = entidad?.rol_financiero === 'finanzas_admin' || hasRole('admin');
  const cargar = useCallback(async () => { if (!entidadId) return; setCargando(true); setError(''); try { const [a, c] = await Promise.all([listarAlertasFinancieras(entidadId), configuracionAlertasFinancieras(entidadId)]); setAlertas(a); setConfig(c); } catch (e) { setError(e.response?.data?.error || 'No se pudieron cargar las alertas financieras.'); } finally { setCargando(false); } }, [entidadId]);
  useEffect(() => { listarEntidadesFinancieras().then((rows) => { setEntidades(rows); setEntidadId((id) => id || String(rows[0]?.id || '')); }).catch((e) => setError(e.response?.data?.error || 'No se pudieron cargar las entidades.')); }, []);
  useEffect(() => { cargar(); }, [cargar]);
  const visibles = useMemo(() => alertas.filter((a) => (!filtros.estado || a.estado === filtros.estado) && (!filtros.tipo || a.tipo === filtros.tipo) && (!filtros.severidad || a.severidad === filtros.severidad)), [alertas, filtros]);
  const cambiar = async (alerta, estado) => { try { await cambiarEstadoAlertaFinanciera(entidadId, alerta.id, estado); notify.success('Alerta actualizada'); await cargar(); } catch (e) { notify.error(e); } };
  const verHistorial = async (alerta) => { try { setHistorial((p) => ({ ...p, [alerta.id]: p[alerta.id] === undefined ? null : undefined })); const h = await historialAlertaFinanciera(entidadId, alerta.id); setHistorial((p) => ({ ...p, [alerta.id]: h })); } catch (e) { notify.error(e); } };
  const guardarConfig = async () => { setGuardando(true); try { const actualizada = await guardarConfiguracionAlertasFinancieras(entidadId, config.map((x) => ({ tipo: x.tipo, activa: x.activa, severidad: x.severidad, umbral_minor: x.umbral_minor }))); setConfig(actualizada); notify.success('Configuración de alertas guardada'); await cargar(); } catch (e) { notify.error(e); } finally { setGuardando(false); } };
  const tipos = [...new Set(alertas.map((x) => x.tipo))];
  return <Box><PageHeader title="Alertas financieras" subtitle="Detecta, atiende y audita riesgos financieros por entidad." />
    {entidades.length > 0 && <TextField select label="Entidad económica" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: { xs: '100%', sm: 320 }, mb: 2 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre} ({e.codigo})</MenuItem>)}</TextField>}
    {error && <Alert severity="error" action={<Button color="inherit" size="small" onClick={cargar}>Reintentar</Button>} sx={{ mb: 2 }}>{error}</Alert>}
    <Paper variant="outlined" sx={{ p: 2, mb: 2, borderRadius: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} spacing={1}><TextField select size="small" label="Estado" value={filtros.estado} onChange={(e) => setFiltros((p) => ({ ...p, estado: e.target.value }))}><MenuItem value="">Todos</MenuItem>{Object.entries(etiquetas).map(([v, l]) => <MenuItem key={v} value={v}>{l}</MenuItem>)}</TextField><TextField select size="small" label="Tipo" value={filtros.tipo} onChange={(e) => setFiltros((p) => ({ ...p, tipo: e.target.value }))}><MenuItem value="">Todos</MenuItem>{tipos.map((v) => <MenuItem key={v} value={v}>{v.replaceAll('_', ' ')}</MenuItem>)}</TextField><TextField select size="small" label="Severidad" value={filtros.severidad} onChange={(e) => setFiltros((p) => ({ ...p, severidad: e.target.value }))}><MenuItem value="">Todas</MenuItem>{Object.keys(tonos).map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField></Stack></Paper>
    {cargando ? <Stack alignItems="center" sx={{ py: 6 }}><CircularProgress /></Stack> : visibles.length === 0 ? <EmptyState title="No hay alertas con estos filtros" subtitle="Cuando se detecte un riesgo financiero aparecerá aquí." /> : <Stack spacing={1.5}>{visibles.map((a) => { let origen = {}; try { origen = JSON.parse(a.origen_json); } catch (_) {} return <Paper key={a.id} variant="outlined" sx={{ p: 2, borderRadius: 3, borderLeft: 5, borderLeftColor: `${tonos[a.severidad]}.main` }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1}><Box><Stack direction="row" spacing={1} sx={{ mb: .75, flexWrap: 'wrap' }}><Chip size="small" color={tonos[a.severidad]} label={a.severidad} /><Chip size="small" variant="outlined" label={etiquetas[a.estado]} /></Stack><Typography fontWeight={700}>{a.mensaje}</Typography><Typography variant="body2" color="text.secondary">{a.tipo.replaceAll('_', ' ')} · Actualizada: {new Date(`${a.actualizada_en}Z`).toLocaleString()}</Typography>{origen.ruta && <Button component={RouterLink} to={origen.ruta} size="small" sx={{ px: 0, mt: .5 }}>Ver origen</Button>}</Box><Stack direction="row" flexWrap="wrap" alignItems="flex-start">{a.estado === 'activa' && <Button size="small" onClick={() => cambiar(a, 'leida')}>Marcar leída</Button>}{['activa', 'leida'].includes(a.estado) && <Button size="small" color="success" onClick={() => cambiar(a, 'resuelta')}>Resolver</Button>}{['activa', 'leida'].includes(a.estado) && <Button size="small" color="warning" onClick={() => cambiar(a, 'ignorada')}>Ignorar</Button>}{['resuelta', 'ignorada'].includes(a.estado) && <Button size="small" onClick={() => cambiar(a, 'activa')}>Reactivar</Button>}<Button size="small" onClick={() => verHistorial(a)}>Historial</Button></Stack></Stack>{historial[a.id] === null && <CircularProgress size={18} sx={{ mt: 1 }} />}{Array.isArray(historial[a.id]) && <Box sx={{ mt: 1.5, pt: 1, borderTop: 1, borderColor: 'divider' }}>{historial[a.id].length ? historial[a.id].map((h) => <Typography key={h.id} variant="body2" color="text.secondary">{new Date(`${h.creado_en}Z`).toLocaleString()}: {h.estado_anterior || 'creada'} → {h.estado_nuevo}{h.usuario ? ` · ${h.usuario}` : ''}</Typography>) : <Typography variant="body2" color="text.secondary">Sin cambios registrados.</Typography>}</Box>}</Paper>; })}</Stack>}
    <Paper variant="outlined" sx={{ p: 2, mt: 3, borderRadius: 3 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }}><Box><Typography variant="h6">Configuración por entidad</Typography><Typography variant="body2" color="text.secondary">Los umbrales de dinero se expresan en céntimos y los de vencimiento en días.</Typography></Box>{puedeConfigurar && <Button variant="contained" disabled={guardando} onClick={guardarConfig}>{guardando ? 'Guardando…' : 'Guardar configuración'}</Button>}</Stack><Divider sx={{ my: 2 }} /><Stack spacing={1}>{config.map((c, i) => <Stack key={c.tipo} direction={{ xs: 'column', md: 'row' }} alignItems={{ md: 'center' }} spacing={1}><FormControlLabel control={<Switch disabled={!puedeConfigurar} checked={Boolean(c.activa)} onChange={(e) => setConfig((p) => p.map((x, n) => n === i ? { ...x, activa: e.target.checked ? 1 : 0 } : x))} />} label={c.etiqueta} sx={{ minWidth: 260 }} /><TextField select size="small" disabled={!puedeConfigurar} label="Severidad" value={c.severidad} onChange={(e) => setConfig((p) => p.map((x, n) => n === i ? { ...x, severidad: e.target.value } : x))}>{Object.keys(tonos).map((v) => <MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField>{(dineroTipos.has(c.tipo) || diasTipos.has(c.tipo)) && <TextField size="small" disabled={!puedeConfigurar} type="number" label={diasTipos.has(c.tipo) ? 'Días' : 'Umbral (céntimos)'} value={c.umbral_minor ?? ''} onChange={(e) => setConfig((p) => p.map((x, n) => n === i ? { ...x, umbral_minor: e.target.value === '' ? null : Number(e.target.value) } : x))} inputProps={{ min: 0 }} />}</Stack>)}</Stack></Paper>
  </Box>;
}
