import { useEffect, useState } from "react";
import { Alert, Box, Grid, MenuItem, Paper, Skeleton, Stack, Typography } from "@mui/material";
import AccountBalanceWalletIcon from "@mui/icons-material/AccountBalanceWalletOutlined";
import AccountTreeIcon from "@mui/icons-material/AccountTreeOutlined";
import WarningAmberIcon from "@mui/icons-material/WarningAmberOutlined";
import PageHeader from "../components/PageHeader";
import KpiCard from "../components/KpiCard";
import DataTable from "../components/DataTable";
import EmptyState from "../components/EmptyState";
import { formatoMoneda } from "../utils/format";
import { dondeEstaMiDinero, listarEntidadesFinancieras } from "../api/endpoints";
import { TextField } from "@mui/material";

const etiquetas = { inventario: "Inventario", impuestos: "Impuestos", marketing: "Marketing", reserva: "Reserva", reinversion: "Reinversión", utilidad: "Utilidad", sin_asignar: "Sin asignar", otros: "Otros" };

export default function DondeEstaMiDineroPage() {
  const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState(""); const [datos, setDatos] = useState(null); const [cargando, setCargando] = useState(true); const [error, setError] = useState("");
  useEffect(() => { listarEntidadesFinancieras().then((rows) => { setEntidades(rows); setEntidadId(rows[0] ? String(rows[0].id) : ""); }).catch((e) => { setError(e.message); setCargando(false); }); }, []);
  useEffect(() => { if (!entidadId) return; setCargando(true); setError(""); dondeEstaMiDinero(entidadId).then(setDatos).catch((e) => setError(e.message)).finally(() => setCargando(false)); }, [entidadId]);
  const vacio = !cargando && !error && (!datos || datos.conciliacion.saldo_fisico_minor === 0);
  return <Box><PageHeader title="Dónde está mi dinero" subtitle="Ubicación física, finalidad asignada y conciliación financiera en tiempo real." /><TextField select label="Entidad" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: 280, mb: 3 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField>
    {error && <Alert severity="error">No se pudo consultar la información financiera: {error}</Alert>}{cargando && <Skeleton variant="rounded" height={280} />}{vacio && <EmptyState title="Aún no hay dinero registrado" description="Registra un saldo inicial, cobro o movimiento financiero para conciliarlo aquí." />}{!cargando && !error && !vacio && <><Grid container spacing={2} sx={{ mb: 3 }}><Grid item xs={12} sm={6} md={3}><KpiCard title="Saldo físico" value={formatoMoneda(datos.conciliacion.saldo_fisico_minor / 100)} icon={<AccountBalanceWalletIcon />} color="info" /></Grid><Grid item xs={12} sm={6} md={3}><KpiCard title="Asignado a bolsillos" value={formatoMoneda(datos.conciliacion.asignado_minor / 100)} icon={<AccountTreeIcon />} color="secondary" /></Grid><Grid item xs={12} sm={6} md={3}><KpiCard title="Diferencia" value={formatoMoneda(datos.conciliacion.diferencia_minor / 100)} icon={<WarningAmberIcon />} color={datos.conciliacion.diferencia_minor === 0 ? "success" : "error"} /></Grid><Grid item xs={12} sm={6} md={3}><KpiCard title="Alertas" value={datos.alertas.length} icon={<WarningAmberIcon />} color={datos.alertas.length ? "warning" : "success"} /></Grid></Grid>
      {datos.alertas.map((a, i) => <Alert key={i} severity="warning" sx={{ mb: 1 }}>{a.tipo === "sin_asignar" ? `Hay ${formatoMoneda(a.importe_minor / 100)} sin asignar a una finalidad.` : `${a.cuenta}: diferencia de ${formatoMoneda(a.importe_minor / 100)} entre saldo físico y bolsillos.`}</Alert>)}
      <Grid container spacing={2.5}><Grid item xs={12} lg={6}><Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography variant="h6" sx={{ mb: 1 }}>Dinero por ubicación</Typography><DataTable searchable={false} rows={datos.ubicaciones} columns={[{ field: "nombre", headerName: "Cuenta" }, { field: "tipo", headerName: "Tipo" }, { field: "saldo_fisico_minor", headerName: "Físico", align: "right", renderCell: (r) => formatoMoneda(r.saldo_fisico_minor / 100) }, { field: "asignado_minor", headerName: "Asignado", align: "right", renderCell: (r) => formatoMoneda(r.asignado_minor / 100) }, { field: "diferencia_minor", headerName: "Diferencia", align: "right", renderCell: (r) => formatoMoneda(r.diferencia_minor / 100) }]} /></Paper></Grid><Grid item xs={12} lg={6}><Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography variant="h6" sx={{ mb: 1 }}>Dinero por finalidad</Typography><DataTable searchable={false} rows={datos.finalidades.filter((x) => x.saldo_minor !== 0)} getRowId={(r) => r.nombre} columns={[{ field: "nombre", headerName: "Finalidad", renderCell: (r) => etiquetas[r.nombre] || r.nombre }, { field: "saldo_minor", headerName: "Monto", align: "right", renderCell: (r) => formatoMoneda(r.saldo_minor / 100) }]} /></Paper></Grid><Grid item xs={12}><Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography variant="h6" sx={{ mb: 1 }}>Bolsillos detallados</Typography><DataTable searchable={false} rows={datos.bolsillos} columns={[{ field: "nombre", headerName: "Bolsillo" }, { field: "finalidad", headerName: "Finalidad", renderCell: (r) => etiquetas[r.finalidad] || r.finalidad }, { field: "saldo_minor", headerName: "Saldo", align: "right", renderCell: (r) => formatoMoneda(r.saldo_minor / 100) }]} /></Paper></Grid></Grid></>}
  </Box>;
}
