import { useEffect, useState } from "react";
import { Alert, Box, Button, Checkbox, FormControlLabel, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import PageHeader from "../components/PageHeader";
import DataTable from "../components/DataTable";
import FormDialog from "../components/FormDialog";
import { cambiarEstadoCatalogoFinanciero, crearBolsillo, crearCuentaFinanciera, crearEntidadFinanciera, listarBolsillos, listarCuentasFinancieras, listarEntidadesFinancieras, listarEventosFinancieros, listarPlanCuentas, saldosBolsillos, saldosContables, saldosTesoreria } from "../api/endpoints";
import { useAuth } from "../context/AuthContext";
import { useNotify } from "../hooks/useNotify";

export default function FinanzasPage() {
  const notify = useNotify(); const { hasRole } = useAuth(); const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState(""); const [tab, setTab] = useState(0); const [modal, setModal] = useState(null); const [saving, setSaving] = useState(false); const [nueva, setNueva] = useState({ codigo: "", nombre: "", tipo: "empresa", fecha_inicial: new Date().toISOString().slice(0, 10) }); const [bolsillo, setBolsillo] = useState({ codigo: "", nombre: "", tipo: "operacion", permite_saldo_negativo: false }); const [cuenta, setCuenta] = useState({ codigo: "", nombre: "", tipo: "caja", cuenta_contable_id: "", titular_legal: "", custodio_propietario_id: "", custodio_entidad_id: "", referencia_externa: "" }); const [datos, setDatos] = useState({ plan: [], cuentas: [], bolsillos: [], tesoreria: [], saldoBolsillos: [], contables: [], eventos: [] });
  useEffect(() => { listarEntidadesFinancieras().then((rows) => { setEntidades(rows); setEntidadId(rows[0]?.id || ""); }).catch(notify.error); }, [notify]);
  useEffect(() => { if (!entidadId) return; Promise.all([listarPlanCuentas(entidadId), listarCuentasFinancieras(entidadId), listarBolsillos(entidadId), saldosTesoreria(entidadId), saldosBolsillos(entidadId), saldosContables(entidadId), listarEventosFinancieros(entidadId)]).then(([plan, cuentas, bolsillos, tesoreria, saldoBolsillos, contables, eventos]) => setDatos({ plan, cuentas, bolsillos, tesoreria, saldoBolsillos, contables, eventos })).catch(notify.error); }, [entidadId, notify]);
  const crearEntidad = async () => { try { await crearEntidadFinanciera(nueva); const rows = await listarEntidadesFinancieras(); setEntidades(rows); setEntidadId(rows[0]?.id || ""); notify.success("Entidad financiera creada"); } catch (e) { notify.error(e); } };
  const recargar = async () => { const [plan, cuentas, bolsillos, tesoreria, saldoBolsillos, contables, eventos] = await Promise.all([listarPlanCuentas(entidadId), listarCuentasFinancieras(entidadId), listarBolsillos(entidadId), saldosTesoreria(entidadId), saldosBolsillos(entidadId), saldosContables(entidadId), listarEventosFinancieros(entidadId)]); setDatos({ plan, cuentas, bolsillos, tesoreria, saldoBolsillos, contables, eventos }); };
  const guardar = async () => { setSaving(true); try { if (modal === "bolsillo") await crearBolsillo(entidadId, bolsillo); if (modal === "cuenta") await crearCuentaFinanciera(entidadId, { ...cuenta, cuenta_contable_id: Number(cuenta.cuenta_contable_id), custodio_propietario_id: cuenta.custodio_propietario_id || null, custodio_entidad_id: cuenta.custodio_entidad_id || null }); await recargar(); setModal(null); notify.success("Registro creado"); } catch (e) { notify.error(e); } finally { setSaving(false); } };
  const cambiarEstado = async (tipo, row) => { try { await cambiarEstadoCatalogoFinanciero(entidadId, tipo, row.id, row.estado === "activa" ? "inactiva" : "activa"); await recargar(); notify.success("Estado actualizado"); } catch (e) { notify.error(e); } };
  if (!entidades.length) return <Box><PageHeader title="Finanzas" /><Alert severity="info" sx={{ mb: 2 }}>No tienes acceso financiero a una entidad.</Alert>{hasRole("admin") && <Paper variant="outlined" sx={{ p: 2, display: "flex", gap: 1, flexWrap: "wrap" }}><TextField label="Código" value={nueva.codigo} onChange={(e) => setNueva((n) => ({ ...n, codigo: e.target.value }))} /><TextField label="Nombre" value={nueva.nombre} onChange={(e) => setNueva((n) => ({ ...n, nombre: e.target.value }))} /><TextField select label="Tipo" value={nueva.tipo} onChange={(e) => setNueva((n) => ({ ...n, tipo: e.target.value }))}><MenuItem value="empresa">Empresa</MenuItem><MenuItem value="persona">Persona</MenuItem><MenuItem value="patrimonio_compartido">Patrimonio compartido</MenuItem></TextField><Button variant="contained" onClick={crearEntidad}>Crear primera entidad</Button></Paper>}</Box>;
  const save = async () => { try { if (modal === "bolsillo") await crearBolsillo(entidadId, bolsillo); else await crearCuentaFinanciera(entidadId, { ...cuenta, cuenta_contable_id: Number(cuenta.cuenta_contable_id) }); setModal(null); window.location.reload(); } catch (e) { notify.error(e); } };
  return <Box><PageHeader title="Finanzas" subtitle="Tesorería, catálogos y eventos financieros." /><TextField select label="Entidad" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: 280, mb: 3 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField><Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 2 }}><Tab label="Tesorería" /><Tab label="Catálogos" /><Tab label="Eventos" /></Tabs>{tab === 0 && <><Stack direction="row" spacing={1} sx={{ mb: 2 }}><Button variant="contained" onClick={() => setModal("cuenta")}>Nueva cuenta financiera</Button><Button variant="outlined" onClick={() => setModal("bolsillo")}>Nuevo bolsillo</Button></Stack><DataTable rows={datos.cuentas} columns={[{ field: "codigo", headerName: "Código" }, { field: "nombre", headerName: "Nombre" }, { field: "tipo", headerName: "Tipo" }, { field: "estado", headerName: "Estado" }]} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Bolsillos</Typography><DataTable rows={datos.bolsillos} columns={[{ field: "codigo", headerName: "Código" }, { field: "nombre", headerName: "Nombre" }, { field: "tipo", headerName: "Tipo" }, { field: "permite_saldo_negativo", headerName: "Saldo negativo" }, { field: "estado", headerName: "Estado" }]} /></>}<FormDialog open={modal === "bolsillo"} title="Nuevo bolsillo" onClose={() => setModal(null)}><Stack spacing={2}><TextField label="Código" value={bolsillo.codigo} onChange={(e) => setBolsillo({ ...bolsillo, codigo: e.target.value })}/><TextField label="Nombre" value={bolsillo.nombre} onChange={(e) => setBolsillo({ ...bolsillo, nombre: e.target.value })}/><Button variant="contained" onClick={save}>Guardar</Button></Stack></FormDialog><FormDialog open={modal === "cuenta"} title="Nueva cuenta financiera" onClose={() => setModal(null)}><Stack spacing={2}><TextField label="Código" value={cuenta.codigo} onChange={(e) => setCuenta({ ...cuenta, codigo: e.target.value })}/><TextField label="Nombre" value={cuenta.nombre} onChange={(e) => setCuenta({ ...cuenta, nombre: e.target.value })}/><TextField select label="Cuenta contable" value={cuenta.cuenta_contable_id} onChange={(e) => setCuenta({ ...cuenta, cuenta_contable_id: e.target.value })}>{datos.plan.map((p) => <MenuItem key={p.id} value={p.id}>{p.codigo} — {p.nombre}</MenuItem>)}</TextField><Button variant="contained" onClick={save}>Guardar</Button></Stack></FormDialog></Box>;
}
