import { useCallback, useEffect, useMemo, useState } from "react";
import { Box, Button, Checkbox, FormControlLabel, Grid, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import PageHeader from "../components/PageHeader";
import DataTable from "../components/DataTable";
import FormDialog from "../components/FormDialog";
import ConfirmDialog from "../components/ConfirmDialog";
import StatusChip from "../components/StatusChip";
import MovimientosManualesTab from "../components/finanzas/MovimientosManualesTab";
import { useAuth } from "../context/AuthContext";
import { useNotify } from "../hooks/useNotify";
import { formatoMoneda, formatoFecha } from "../utils/format";
import {
  cambiarEstadoCatalogoFinanciero, cerrarPeriodoFinanciero, crearBolsillo, crearCuentaFinanciera,
  crearCuentaPlan, crearEntidadFinanciera, crearParticipacionFinanciera, crearPropietarioFinanciero,
  listarAccesosFinancieros, listarBolsillos, listarCuentasFinancieras, listarEntidadesFinancieras,
  listarEventosFinancieros, listarParticipacionesFinancieras, listarPeriodosFinancieros, listarPlanCuentas,
  listarPropietariosFinancieros, obtenerEventoFinanciero, otorgarAccesoFinanciero, reasignarBolsillo,
  registrarSaldoInicial, registrarTransferenciaFinanciera, respaldoCuentaBolsillo, revertirEventoFinanciero,
  saldosBolsillos, saldosContables, saldosTesoreria, listarUsuarios, listarPoliticasFinancieras,
  crearPoliticaFinanciera, activarPoliticaFinanciera, simularPoliticaFinanciera, aplicarPlantillaFinanciera, historialPoliticaFinanciera, listarMetasFinancieras, listarAlertasFinancieras,
} from "../api/endpoints";

const hoy = () => new Date().toISOString().slice(0, 10);
const uid = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const naturales = ["activo", "pasivo", "patrimonio", "ingreso", "costo", "gasto"];
const subtipos = ["efectivo_equivalente", "custodia_tercero", "fondos_procesador", "cuentas_por_cobrar", "inventario", "otro_activo", "cuentas_por_pagar", "otro_pasivo", "capital", "resultados_acumulados", "saldo_inicial", "ingreso_operativo", "otro_ingreso", "costo_ventas", "otro_costo", "gasto_operativo", "gasto_financiero", "otro_gasto"];
const tiposCuenta = ["caja", "banco", "billetera", "procesador", "custodia_tercero", "transito"];
const tiposBolsillo = ["operacion", "reserva", "impuestos", "otro"];
const rolesFinancieros = ["finanzas_admin", "finanzas_operador", "finanzas_lector", "finanzas_personal_propietario", "finanzas_auditor_personal"];

function Campos({ fields, data, setData }) {
  return <Grid container spacing={2}>{fields.map((f) => <Grid item xs={12} sm={f.half ? 6 : 12} key={f.name}>
    {f.check ? <FormControlLabel control={<Checkbox checked={Boolean(data[f.name])} onChange={(e) => setData((p) => ({ ...p, [f.name]: e.target.checked }))} />} label={f.label} /> :
      <TextField fullWidth required={f.required} label={f.label} value={data[f.name] ?? ""} type={f.type || "text"} select={Boolean(f.options)}
        inputProps={f.type === "number" ? { step: f.step || "any", min: f.min } : undefined}
        onChange={(e) => setData((p) => ({ ...p, [f.name]: e.target.value }))}>
        {f.options?.map((o) => <MenuItem key={o.value ?? o} value={o.value ?? o}>{o.label ?? o}</MenuItem>)}
      </TextField>}
  </Grid>)}</Grid>;
}

export default function FinanzasPage() {
  const notify = useNotify(); const { hasRole } = useAuth(); const esAdminSistema = hasRole("admin");
  const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState("");
  const [datos, setDatos] = useState({ plan: [], cuentas: [], bolsillos: [], tesoreria: [], saldoBolsillos: [], contables: [], respaldo: [], eventos: [], periodos: [], participaciones: [], accesos: [], politicas: [], alertas: [] });
  const [propietarios, setPropietarios] = useState([]); const [usuarios, setUsuarios] = useState([]); const [metasActivas, setMetasActivas] = useState([]);
  const [tab, setTab] = useState(0); const [modal, setModal] = useState(null); const [form, setForm] = useState({}); const [eventoDetalle, setEventoDetalle] = useState(null); const [eventoARevertir, setEventoARevertir] = useState(null); const [filtrosEventos, setFiltrosEventos] = useState({ fecha: "", tipo: "", estado: "" }); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true); const [mpfAbierto, setMpfAbierto] = useState(false); const [mpf, setMpf] = useState({ nombre: "Ventas DL8", importe: "100", reglas: [] }); const [simulacion, setSimulacion] = useState(null);
  const entidad = useMemo(() => entidades.find((e) => String(e.id) === String(entidadId)), [entidades, entidadId]);
  const esFinAdmin = entidad?.rol_financiero === "finanzas_admin";
  const puedeOperar = entidad && ["finanzas_admin", "finanzas_operador", "finanzas_personal_propietario"].includes(entidad.rol_financiero);
  const cargarEntidades = useCallback(async () => { const rows = await listarEntidadesFinancieras(); setEntidades(rows); setEntidadId((id) => id || (rows[0] ? String(rows[0].id) : "")); }, []);
  const cargarDatos = useCallback(async () => {
    if (!entidadId) { setLoading(false); return; } setLoading(true);
    try {
      const base = await Promise.all([listarPlanCuentas(entidadId), listarCuentasFinancieras(entidadId), listarBolsillos(entidadId), saldosTesoreria(entidadId), saldosBolsillos(entidadId), saldosContables(entidadId), respaldoCuentaBolsillo(entidadId), listarEventosFinancieros(entidadId), listarPeriodosFinancieros(entidadId), listarParticipacionesFinancieras(entidadId), listarPoliticasFinancieras(entidadId), listarAlertasFinancieras(entidadId)]);
      let accesos = []; try { accesos = await listarAccesosFinancieros(entidadId); } catch (_) { /* Solo administración financiera puede verlos. */ }
      setDatos({ plan: base[0], cuentas: base[1], bolsillos: base[2], tesoreria: base[3], saldoBolsillos: base[4], contables: base[5], respaldo: base[6], eventos: base[7], periodos: base[8], participaciones: base[9], politicas: base[10], alertas: base[11], accesos });
    } catch (e) { notify.error(e); } finally { setLoading(false); }
  }, [entidadId, notify]);
  useEffect(() => { cargarEntidades().catch(notify.error); }, [cargarEntidades, notify]);
  useEffect(() => { cargarDatos(); }, [cargarDatos]);
  useEffect(() => { if (entidadId) listarMetasFinancieras(entidadId).then((m) => setMetasActivas(m.filter((x) => x.estado === "activa"))).catch(() => setMetasActivas([])); }, [entidadId]);
  useEffect(() => { if (esAdminSistema) Promise.all([listarPropietariosFinancieros(), listarUsuarios()]).then(([p, u]) => { setPropietarios(p); setUsuarios(u); }).catch(notify.error); }, [esAdminSistema, notify]);

  const abrir = (nombre) => {
    const inicial = {
      entidad: { codigo: "", nombre: "", tipo: "empresa", fecha_inicial: hoy() }, propietario: { tipo: "persona", nombre: "", documento_tipo: "", documento_numero: "", usuario_id: "" },
      plan: { codigo: "", nombre: "", naturaleza: "activo", subtipo: "otro_activo", permite_movimiento: true },
      cuenta: { codigo: "", nombre: "", tipo: "caja", cuenta_contable_id: "", titular_legal: "", custodio_propietario_id: "", custodio_entidad_id: "", referencia_externa: "" },
      bolsillo: { codigo: "", nombre: "", tipo: "operacion", permite_saldo_negativo: false },
      inicial: { fecha: hoy(), cuenta_financiera_id: "", bolsillo_id: "", importe: "", descripcion: "Saldo inicial" },
      transferencia: { fecha: hoy(), cuenta_origen_id: "", cuenta_destino_id: "", bolsillo_origen_id: "", bolsillo_destino_id: "", importe: "", descripcion: "Transferencia interna" },
      reasignar: { fecha: hoy(), cuenta_financiera_id: "", bolsillo_origen_id: "", bolsillo_destino_id: "", importe: "", descripcion: "Reasignación de fondos" },
      participacion: { propietario_id: "", porcentaje: "", cuenta_capital_id: "", fecha_inicio: hoy(), fecha_fin: "" }, acceso: { usuario_id: "", rol_financiero: "finanzas_lector" },
    }; setForm(inicial[nombre]); setModal(nombre);
  };
  const guardar = async () => {
    setSaving(true); try {
      if (modal === "entidad") { await crearEntidadFinanciera(form); await cargarEntidades(); }
      else if (modal === "propietario") await crearPropietarioFinanciero({ ...form, usuario_id: form.usuario_id || null });
      else if (modal === "plan") await crearCuentaPlan(entidadId, form);
      else if (modal === "cuenta") await crearCuentaFinanciera(entidadId, { ...form, cuenta_contable_id: Number(form.cuenta_contable_id), custodio_propietario_id: form.custodio_propietario_id || null, custodio_entidad_id: form.custodio_entidad_id || null });
      else if (modal === "bolsillo") await crearBolsillo(entidadId, form);
      else if (modal === "participacion") await crearParticipacionFinanciera(entidadId, { propietario_id: Number(form.propietario_id), porcentaje_minor: form.porcentaje === "" ? null : Math.round(Number(form.porcentaje) * 100), cuenta_capital_id: form.cuenta_capital_id ? Number(form.cuenta_capital_id) : null, fecha_inicio: form.fecha_inicio, fecha_fin: form.fecha_fin || null });
      else if (modal === "acceso") await otorgarAccesoFinanciero(entidadId, { ...form, usuario_id: Number(form.usuario_id) });
      else { const payload = { ...form, importe_minor: Math.round(Number(form.importe) * 100) }; delete payload.importe; if (modal === "inicial") await registrarSaldoInicial(entidadId, payload, uid()); if (modal === "transferencia") await registrarTransferenciaFinanciera(entidadId, payload, uid()); if (modal === "reasignar") await reasignarBolsillo(entidadId, payload, uid()); }
      notify.success("Operación registrada"); setModal(null); await cargarDatos(); if (modal === "propietario") setPropietarios(await listarPropietariosFinancieros());
    } catch (e) { notify.error(e); } finally { setSaving(false); }
  };
  const cambiarEstado = async (tipo, row, estado) => { try { await cambiarEstadoCatalogoFinanciero(entidadId, tipo, row.id, estado); notify.success("Estado actualizado"); cargarDatos(); } catch (e) { notify.error(e); } };
  const cerrarPeriodo = async (periodo) => { try { await cerrarPeriodoFinanciero(entidadId, periodo.id); notify.success("Período cerrado"); cargarDatos(); } catch (e) { notify.error(e); } };
  const verEvento = async (row) => { try { const [evento, politica] = await Promise.all([obtenerEventoFinanciero(entidadId, row.id), historialPoliticaFinanciera(entidadId, row.id)]); setEventoDetalle({ ...evento, politica_financiera: politica }); } catch (e) { notify.error(e); } };
  const revertir = async () => { if (!eventoARevertir) return; try { await revertirEventoFinanciero(entidadId, eventoARevertir.id, uid()); notify.success("Evento revertido"); setEventoARevertir(null); cargarDatos(); } catch (e) { notify.error(e); } };
  const abrirMpf = () => { const primerBolsillo = datos.bolsillos.find((b) => b.estado === "activa" && b.tipo !== "sin_asignar"); setMpf({ nombre: "Ventas DL8", importe: "100", reglas: primerBolsillo ? [{ nombre: "Utilidad", bolsillo_id: String(primerBolsillo.id), porcentaje: "100" }] : [] }); setSimulacion(null); setMpfAbierto(true); };
  const guardarMpf = async () => { try { if (!mpf.reglas.length) throw new Error("Agrega al menos una regla"); const politica = await crearPoliticaFinanciera(entidadId, { nombre: mpf.nombre, evento_tipo: "cobro_venta", reglas: mpf.reglas.map((r) => ({ nombre: r.nombre, bolsillo_id: Number(r.bolsillo_id), base: "ingreso", tipo: "porcentaje", valor_minor: Math.round(Number(r.porcentaje) * 100) })) }); const resultado = await simularPoliticaFinanciera(entidadId, politica.id, Math.round(Number(mpf.importe) * 100)); setSimulacion({ ...resultado, politica_id: politica.id }); await cargarDatos(); notify.success("Política guardada como borrador"); } catch (e) { notify.error(e); } };
  const activarMpf = async (politicaId) => { try { await activarPoliticaFinanciera(entidadId, politicaId, true); notify.success("Política activada para cobros de venta"); await cargarDatos(); } catch (e) { notify.error(e); } };
  const aplicarPlantilla = async (codigo) => { try { const respuesta = await aplicarPlantillaFinanciera(entidadId, codigo); notify.success(respuesta.existente ? "La plantilla ya estaba creada" : "Plantilla creada como borrador"); await cargarDatos(); } catch (e) { notify.error(e); } };
  const simularMpf = async (politica) => { const importe = globalThis.prompt("Importe de venta a simular (S/)", "100"); if (importe == null || !(Number(importe) > 0)) return; try { const resultado = await simularPoliticaFinanciera(entidadId, politica.id, Math.round(Number(importe) * 100)); setSimulacion(resultado); setMpfAbierto(true); } catch (e) { notify.error(e); } };
  const cuentasSaldo = datos.cuentas.map((c) => ({ ...c, saldo_minor: datos.tesoreria.find((s) => s.id === c.id)?.saldo_minor || 0 }));
  const bolsilloSaldo = datos.bolsillos.map((b) => ({ ...b, saldo_minor: datos.saldoBolsillos.find((s) => s.id === b.id)?.saldo_minor || 0 }));
  const eventosFiltrados = datos.eventos.filter((evento) => (!filtrosEventos.fecha || String(evento.fecha).startsWith(filtrosEventos.fecha)) && (!filtrosEventos.tipo || evento.tipo === filtrosEventos.tipo) && (!filtrosEventos.estado || evento.estado === filtrosEventos.estado));
  const tiposEvento = [...new Set(datos.eventos.map((evento) => evento.tipo).filter(Boolean))];
  const opcionesCuenta = datos.cuentas.filter((x) => x.estado === "activa").map((x) => ({ value: x.id, label: x.nombre })); const opcionesBolsillo = datos.bolsillos.filter((x) => x.estado === "activa").map((x) => ({ value: x.id, label: x.nombre }));
  const titulo = { entidad: "Nueva entidad económica", propietario: "Nuevo propietario", plan: "Nueva cuenta contable", cuenta: "Nueva cuenta financiera", bolsillo: "Nuevo bolsillo", inicial: "Registrar saldo inicial", transferencia: "Transferir fondos", reasignar: "Reasignar entre bolsillos", participacion: "Nueva participación", acceso: "Otorgar acceso financiero" }[modal];
  const fields = modal === "entidad" ? [{ name: "codigo", label: "Código", required: true, half: true }, { name: "nombre", label: "Nombre", required: true, half: true }, { name: "tipo", label: "Tipo", options: ["empresa", "persona", "patrimonio_compartido"], half: true }, { name: "fecha_inicial", label: "Fecha inicial", type: "date", half: true }]
    : modal === "propietario" ? [{ name: "tipo", label: "Tipo", options: ["persona", "organizacion"], half: true }, { name: "nombre", label: "Nombre", required: true, half: true }, { name: "documento_tipo", label: "Tipo de documento", half: true }, { name: "documento_numero", label: "Número de documento", half: true }, { name: "usuario_id", label: "Usuario vinculado", options: [{ value: "", label: "Sin vincular" }, ...usuarios.map((u) => ({ value: u.id, label: u.nombre }))] }]
    : modal === "plan" ? [{ name: "codigo", label: "Código", required: true, half: true }, { name: "nombre", label: "Nombre", required: true, half: true }, { name: "naturaleza", label: "Naturaleza", options: naturales, half: true }, { name: "subtipo", label: "Subtipo", options: subtipos, half: true }, { name: "permite_movimiento", label: "Permite movimientos", check: true }]
    : modal === "cuenta" ? [{ name: "codigo", label: "Código", required: true, half: true }, { name: "nombre", label: "Nombre", required: true, half: true }, { name: "tipo", label: "Tipo", options: tiposCuenta, half: true }, { name: "cuenta_contable_id", label: "Cuenta contable", options: datos.plan.filter((p) => p.estado === "activa").map((p) => ({ value: p.id, label: `${p.codigo} — ${p.nombre}` })) }, { name: "titular_legal", label: "Titular legal", half: true }, { name: "referencia_externa", label: "Referencia externa", half: true }, { name: "custodio_propietario_id", label: "Custodio propietario", options: [{ value: "", label: "Ninguno" }, ...propietarios.map((p) => ({ value: p.id, label: p.nombre }))], half: true }, { name: "custodio_entidad_id", label: "Custodio entidad", options: [{ value: "", label: "Ninguna" }, ...entidades.map((e) => ({ value: e.id, label: e.nombre }))], half: true }]
    : modal === "bolsillo" ? [{ name: "codigo", label: "Código", required: true, half: true }, { name: "nombre", label: "Nombre", required: true, half: true }, { name: "tipo", label: "Tipo", options: tiposBolsillo }, { name: "permite_saldo_negativo", label: "Permitir saldo negativo", check: true }]
    : modal === "participacion" ? [{ name: "propietario_id", label: "Propietario", options: propietarios.map((p) => ({ value: p.id, label: p.nombre })) }, { name: "porcentaje", label: "Participación (%)", type: "number", min: 0, step: 0.01 }, { name: "cuenta_capital_id", label: "Cuenta de capital", options: [{ value: "", label: "Sin cuenta" }, ...datos.plan.filter((p) => p.subtipo === "capital").map((p) => ({ value: p.id, label: p.nombre }))] }, { name: "fecha_inicio", label: "Inicio", type: "date", half: true }, { name: "fecha_fin", label: "Fin (opcional)", type: "date", half: true }]
    : modal === "acceso" ? [{ name: "usuario_id", label: "Usuario", options: usuarios.map((u) => ({ value: u.id, label: u.nombre })) }, { name: "rol_financiero", label: "Rol financiero", options: rolesFinancieros }]
    : modal === "inicial" ? [{ name: "fecha", label: "Fecha", type: "date", half: true }, { name: "importe", label: "Importe (S/)", type: "number", min: 0.01, half: true }, { name: "cuenta_financiera_id", label: "Cuenta", options: opcionesCuenta }, { name: "bolsillo_id", label: "Bolsillo", options: opcionesBolsillo }, { name: "descripcion", label: "Descripción" }]
    : modal === "transferencia" ? [{ name: "fecha", label: "Fecha", type: "date", half: true }, { name: "importe", label: "Importe (S/)", type: "number", min: 0.01, half: true }, { name: "cuenta_origen_id", label: "Cuenta origen", options: opcionesCuenta }, { name: "cuenta_destino_id", label: "Cuenta destino", options: opcionesCuenta }, { name: "bolsillo_origen_id", label: "Bolsillo origen", options: opcionesBolsillo }, { name: "bolsillo_destino_id", label: "Bolsillo destino", options: opcionesBolsillo }, { name: "descripcion", label: "Descripción" }]
    : [{ name: "fecha", label: "Fecha", type: "date", half: true }, { name: "importe", label: "Importe (S/)", type: "number", min: 0.01, half: true }, { name: "cuenta_financiera_id", label: "Cuenta", options: opcionesCuenta }, { name: "bolsillo_origen_id", label: "Bolsillo origen", options: opcionesBolsillo }, { name: "bolsillo_destino_id", label: "Bolsillo destino", options: opcionesBolsillo }, { name: "descripcion", label: "Descripción" }];
  const columnasEstado = (tipo) => [{ field: "codigo", headerName: "Código" }, { field: "nombre", headerName: "Nombre", minWidth: 180 }, { field: "estado", headerName: "Estado", renderCell: (r) => <StatusChip label={r.estado} tone={r.estado === "activa" ? "success" : r.estado === "bloqueada" ? "warning" : "default"} /> }, { field: "acciones", headerName: "", sortable: false, renderCell: (r) => esFinAdmin ? <Stack direction="row"><Button size="small" disabled={r.estado === "activa"} onClick={() => cambiarEstado(tipo, r, "activa")}>Activar</Button><Button size="small" disabled={r.estado === "bloqueada"} onClick={() => cambiarEstado(tipo, r, "bloqueada")}>Bloquear</Button><Button size="small" color="error" disabled={r.estado === "inactiva"} onClick={() => cambiarEstado(tipo, r, "inactiva")}>Inactivar</Button></Stack> : null }];
  return <Box><PageHeader title="Finanzas" subtitle="Entidades, tesorería, contabilidad, gobierno y auditoría financiera." actionLabel={esAdminSistema ? "Nueva entidad" : null} onAction={() => abrir("entidad")} />
    {entidades.length > 0 && <TextField select label="Entidad económica" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: 300, mb: 3 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre} ({e.codigo})</MenuItem>)}</TextField>}
    {entidad && <Paper variant="outlined" sx={{ p: 2, mb: 2, borderRadius: 3 }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between"><Box><Typography variant="subtitle1">Resumen de alertas</Typography><Typography variant="body2" color="text.secondary">{datos.alertas.filter((a) => ["activa", "leida"].includes(a.estado)).length} alertas abiertas · {datos.alertas.filter((a) => a.estado === "activa" && a.severidad === "critica").length} críticas</Typography></Box><Button href="/alertas-financieras" variant="outlined">Gestionar alertas</Button></Stack></Paper>}
    {!entidad ? <Paper variant="outlined" sx={{ p: 4, borderRadius: 3 }}><Typography>No tienes acceso a una entidad financiera.</Typography></Paper> : <>
      <Grid container spacing={2} sx={{ mb: 3 }}><Grid item xs={12} sm={6}><Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography color="text.secondary" variant="body2">Fondos en tesorería</Typography><Typography variant="h5">{formatoMoneda(cuentasSaldo.reduce((a, c) => a + c.saldo_minor, 0) / 100)}</Typography></Paper></Grid><Grid item xs={12} sm={6}><Paper variant="outlined" sx={{ p: 2, borderRadius: 3 }}><Typography color="text.secondary" variant="body2">Rol financiero</Typography><Typography variant="h6">{entidad.rol_financiero}</Typography></Paper></Grid></Grid>
      {metasActivas.length > 0 && <Paper variant="outlined" sx={{ p: 2, borderRadius: 3, mb: 3 }}><Typography variant="subtitle2" sx={{ mb: 1 }}>Metas financieras activas</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={2} flexWrap="wrap" useFlexGap>{metasActivas.map((m) => <Typography key={m.id} variant="body2">{m.nombre}: {m.porcentaje_avance_minor / 100}% · {formatoMoneda(m.saldo_acumulado_minor / 100)} / {formatoMoneda(m.monto_objetivo_minor / 100)}</Typography>)}</Stack></Paper>}
      <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 2 }} variant="scrollable"><Tab label="Tesorería" /><Tab label="Catálogos" /><Tab label="Movimientos" /><Tab label="Movimientos manuales" /><Tab label="Gobierno" /><Tab label="Políticas financieras" /></Tabs>
      {tab === 0 && <><Stack direction="row" spacing={1} sx={{ mb: 2 }}><Button variant="contained" startIcon={<AddIcon />} disabled={!puedeOperar} onClick={() => abrir("inicial")}>Saldo inicial</Button><Button variant="outlined" disabled={!puedeOperar} onClick={() => abrir("transferencia")}>Transferir</Button><Button variant="outlined" disabled={!puedeOperar} onClick={() => abrir("reasignar")}>Reasignar bolsillo</Button></Stack><DataTable loading={loading} rows={cuentasSaldo} columns={[{ field: "codigo", headerName: "Código" }, { field: "nombre", headerName: "Cuenta" }, { field: "tipo", headerName: "Tipo" }, { field: "saldo_minor", headerName: "Saldo", align: "right", renderCell: (r) => formatoMoneda(r.saldo_minor / 100) }]} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Bolsillos y respaldo</Typography><DataTable loading={loading} rows={bolsilloSaldo} searchable={false} columns={[{ field: "codigo", headerName: "Código" }, { field: "nombre", headerName: "Bolsillo" }, { field: "saldo_minor", headerName: "Asignado", renderCell: (r) => formatoMoneda(r.saldo_minor / 100) }, { field: "respaldo", headerName: "Respaldo", renderCell: (r) => formatoMoneda(datos.respaldo.filter((x) => x.bolsillo_id === r.id).reduce((s, x) => s + x.saldo_minor, 0) / 100) }]} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Saldos contables</Typography><DataTable loading={loading} rows={datos.contables.map((x) => ({ ...x, cuenta: datos.plan.find((p) => p.id === x.cuenta_contable_id)?.nombre || x.cuenta_contable_id }))} searchable={false} columns={[{ field: "cuenta", headerName: "Cuenta" }, { field: "saldo_minor", headerName: "Saldo", renderCell: (r) => formatoMoneda(r.saldo_minor / 100) }]} /></>}
      {tab === 1 && <><Stack direction="row" spacing={1} sx={{ mb: 2 }}><Button variant="contained" disabled={!esFinAdmin} onClick={() => abrir("plan")}>Nueva cuenta contable</Button><Button variant="outlined" disabled={!esFinAdmin} onClick={() => abrir("cuenta")}>Nueva cuenta financiera</Button><Button variant="outlined" disabled={!esFinAdmin} onClick={() => abrir("bolsillo")}>Nuevo bolsillo</Button></Stack><Typography variant="h6" sx={{ mb: 1 }}>Plan de cuentas</Typography><DataTable loading={loading} rows={datos.plan} columns={columnasEstado("plan-cuentas")} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Cuentas financieras</Typography><DataTable loading={loading} rows={datos.cuentas} columns={columnasEstado("cuentas-financieras")} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Bolsillos</Typography><DataTable loading={loading} rows={datos.bolsillos} columns={columnasEstado("bolsillos")} /></>}
      {tab === 2 && <><Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ mb: 2 }}><TextField type="date" size="small" label="Fecha" InputLabelProps={{ shrink: true }} value={filtrosEventos.fecha} onChange={(e) => setFiltrosEventos((f) => ({ ...f, fecha: e.target.value }))} /><TextField select size="small" label="Tipo" value={filtrosEventos.tipo} onChange={(e) => setFiltrosEventos((f) => ({ ...f, tipo: e.target.value }))}><MenuItem value="">Todos</MenuItem>{tiposEvento.map((tipo) => <MenuItem key={tipo} value={tipo}>{tipo}</MenuItem>)}</TextField><TextField select size="small" label="Estado" value={filtrosEventos.estado} onChange={(e) => setFiltrosEventos((f) => ({ ...f, estado: e.target.value }))}><MenuItem value="">Todos</MenuItem><MenuItem value="confirmado">Confirmado</MenuItem><MenuItem value="revertido">Revertido</MenuItem></TextField></Stack><DataTable loading={loading} rows={eventosFiltrados} defaultOrderBy="id" defaultOrder="desc" onRowClick={verEvento} columns={[{ field: "id", headerName: "#" }, { field: "fecha", headerName: "Fecha", renderCell: (r) => formatoFecha(r.fecha) }, { field: "tipo", headerName: "Tipo" }, { field: "descripcion", headerName: "Descripción", minWidth: 220 }, { field: "estado", headerName: "Estado", renderCell: (r) => <StatusChip label={r.estado} tone={r.estado === "revertido" ? "error" : "success"} /> }, { field: "acciones", headerName: "", sortable: false, renderCell: (r) => r.estado === "confirmado" && ["finanzas_admin", "finanzas_personal_propietario"].includes(entidad.rol_financiero) ? <Button size="small" color="error" onClick={(e) => { e.stopPropagation(); setEventoARevertir(r); }}>Revertir</Button> : null }]} /></>}
      {tab === 3 && <MovimientosManualesTab />}
      {tab === 4 && <><Stack direction="row" spacing={1} sx={{ mb: 2 }}><Button variant="contained" disabled={!esAdminSistema} onClick={() => abrir("propietario")}>Nuevo propietario</Button><Button variant="outlined" disabled={!esFinAdmin || !esAdminSistema} onClick={() => abrir("participacion")}>Nueva participación</Button><Button variant="outlined" disabled={!esFinAdmin || !esAdminSistema} onClick={() => abrir("acceso")}>Otorgar acceso</Button></Stack><Typography variant="h6" sx={{ mb: 1 }}>Períodos financieros</Typography><DataTable loading={loading} rows={datos.periodos} searchable={false} columns={[{ field: "anio", headerName: "Año" }, { field: "mes", headerName: "Mes" }, { field: "estado", headerName: "Estado", renderCell: (r) => <StatusChip label={r.estado} tone={r.estado === "abierto" ? "success" : "default"} /> }, { field: "acciones", headerName: "", sortable: false, renderCell: (r) => esFinAdmin && r.estado === "abierto" ? <Button size="small" color="warning" onClick={() => cerrarPeriodo(r)}>Cerrar</Button> : null }]} /><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Participaciones</Typography><DataTable loading={loading} rows={datos.participaciones.map((p) => ({ ...p, propietario: propietarios.find((x) => x.id === p.propietario_id)?.nombre || `#${p.propietario_id}`, porcentaje: p.porcentaje_minor == null ? "—" : `${p.porcentaje_minor / 100}%` }))} searchable={false} columns={[{ field: "propietario", headerName: "Propietario" }, { field: "porcentaje", headerName: "Participación" }, { field: "fecha_inicio", headerName: "Inicio" }, { field: "fecha_fin", headerName: "Fin" }]} />{esFinAdmin && <><Typography variant="h6" sx={{ mt: 3, mb: 1 }}>Accesos financieros</Typography><DataTable loading={loading} rows={datos.accesos.map((a) => ({ ...a, usuario: usuarios.find((u) => u.id === a.usuario_id)?.nombre || `#${a.usuario_id}` }))} searchable={false} columns={[{ field: "usuario", headerName: "Usuario" }, { field: "rol_financiero", headerName: "Rol" }, { field: "estado", headerName: "Estado" }]} /></>}</>}
      {tab === 5 && <><Paper variant="outlined" sx={{ p: 2, mb: 2, borderRadius: 3 }}><Typography variant="h6">¿Cómo debe separar el ERP cada cobro?</Typography><Typography color="text.secondary" variant="body2" sx={{ mb: 2 }}>Crea una política, simúlala y actívala cuando el reparto sea correcto. El dinero no sale de la cuenta donde el cliente pagó.</Typography><Button variant="contained" startIcon={<AddIcon />} disabled={!esFinAdmin} onClick={abrirMpf}>Nueva política</Button></Paper><DataTable loading={loading} rows={datos.politicas} columns={[{ field: "nombre", headerName: "Política", minWidth: 180 }, { field: "version", headerName: "Versión" }, { field: "reglas", headerName: "Reglas" }, { field: "estado", headerName: "Estado", renderCell: (r) => <StatusChip label={r.estado} tone={r.estado === "activa" ? "success" : "default"} /> }, { field: "es_predeterminada", headerName: "Cobros", renderCell: (r) => r.es_predeterminada ? "Activa" : "—" }, { field: "acciones", headerName: "", sortable: false, renderCell: (r) => <Stack direction="row"><Button size="small" onClick={() => simularMpf(r)}>Simular</Button>{esFinAdmin && <Button size="small" disabled={r.estado === "activa" && r.es_predeterminada} onClick={() => activarMpf(r.id)}>Activar</Button>}</Stack> }]} /></>}
    </>}
    <FormDialog open={Boolean(modal)} title={titulo} onClose={() => setModal(null)} maxWidth="md"><Campos fields={fields} data={form} setData={setForm} /><Stack direction="row" justifyContent="flex-end" spacing={1} sx={{ mt: 3 }}><Button onClick={() => setModal(null)}>Cancelar</Button><Button variant="contained" disabled={saving} onClick={guardar}>{saving ? "Guardando…" : "Guardar"}</Button></Stack></FormDialog>
    <FormDialog open={mpfAbierto} title="Asistente de política financiera" onClose={() => setMpfAbierto(false)} maxWidth="md"><Stack spacing={2}><Typography color="text.secondary">Define qué porcentaje de cada cobro recibido debe reservar el ERP. Guarda como borrador, simula y luego actívala.</Typography><TextField label="Nombre de la política" value={mpf.nombre || ""} onChange={(e) => setMpf((p) => ({ ...p, nombre: e.target.value }))} /><TextField label="Venta a simular (S/)" type="number" inputProps={{ min: 0.01, step: 0.01 }} value={mpf.importe || ""} onChange={(e) => setMpf((p) => ({ ...p, importe: e.target.value }))} />{mpf.reglas.map((r, i) => <Stack key={i} direction={{ xs: "column", sm: "row" }} spacing={1}><TextField label="Destino" value={r.nombre} onChange={(e) => setMpf((p) => ({ ...p, reglas: p.reglas.map((x, n) => n === i ? { ...x, nombre: e.target.value } : x) }))} /><TextField select label="Bolsillo" value={r.bolsillo_id} onChange={(e) => setMpf((p) => ({ ...p, reglas: p.reglas.map((x, n) => n === i ? { ...x, bolsillo_id: e.target.value } : x) }))} sx={{ minWidth: 180 }}>{opcionesBolsillo.map((b) => <MenuItem key={b.value} value={b.value}>{b.label}</MenuItem>)}</TextField><TextField label="%" type="number" inputProps={{ min: 0, max: 100, step: 0.01 }} value={r.porcentaje} onChange={(e) => setMpf((p) => ({ ...p, reglas: p.reglas.map((x, n) => n === i ? { ...x, porcentaje: e.target.value } : x) }))} /><Button color="error" onClick={() => setMpf((p) => ({ ...p, reglas: p.reglas.filter((_, n) => n !== i) }))}>Quitar</Button></Stack>)}<Button onClick={() => setMpf((p) => ({ ...p, reglas: [...p.reglas, { nombre: "Reserva", bolsillo_id: opcionesBolsillo[0]?.value || "", porcentaje: "0" }] }))}>Agregar destino</Button>{simulacion && <Paper variant="outlined" sx={{ p: 2 }}><Typography variant="subtitle2">Resultado de simulación</Typography>{simulacion.detalles.map((d) => <Typography key={d.regla_id}>{d.nombre}: {formatoMoneda(d.importe_minor / 100)}</Typography>)}<Typography sx={{ mt: 1 }}>Disponible sin asignar: {formatoMoneda(simulacion.disponible_minor / 100)}</Typography>{simulacion.politica_id && <Button sx={{ mt: 1 }} variant="contained" onClick={() => activarMpf(simulacion.politica_id)}>Activar esta política</Button>}</Paper>}<Stack direction="row" justifyContent="flex-end" spacing={1}><Button onClick={() => setMpfAbierto(false)}>Cerrar</Button><Button variant="contained" onClick={guardarMpf}>Guardar y simular</Button></Stack></Stack></FormDialog>
    <FormDialog open={Boolean(eventoDetalle)} title="Detalle del evento financiero" onClose={() => setEventoDetalle(null)} maxWidth="md"><Box component="pre" sx={{ whiteSpace: "pre-wrap", fontSize: 12, m: 0 }}>{JSON.stringify(eventoDetalle, null, 2)}</Box></FormDialog>
    <ConfirmDialog open={Boolean(eventoARevertir)} title="Revertir evento financiero" message={`¿Revertir el evento #${eventoARevertir?.id}? Se registrará una reversión auditable.`} confirmText="Revertir" danger onClose={() => setEventoARevertir(null)} onConfirm={revertir} />
  </Box>;
}
