import { useEffect, useState } from "react";
import { Box, Button, Grid, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import PageHeader from "../components/PageHeader";
import { useNotify } from "../hooks/useNotify";
import { listarBolsillos, listarCuentasFinancieras, listarEntidadesFinancieras, registrarAporteSocio, registrarPrestamoRecibido } from "../api/endpoints";

const hoy = () => new Date().toISOString().slice(0, 10);
const clave = () => globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;

export default function MovimientosEspecialesPage() {
  const notify = useNotify(); const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState(""); const [cuentas, setCuentas] = useState([]); const [bolsillos, setBolsillos] = useState([]);
  const [aporte, setAporte] = useState({ fecha: hoy(), importe: "", cuenta_financiera_id: "", bolsillo_id: "", descripcion: "Aporte de socio" }); const [prestamo, setPrestamo] = useState({ fecha: hoy(), importe: "", cuenta_financiera_id: "", bolsillo_id: "", descripcion: "Préstamo recibido" });
  useEffect(() => { listarEntidadesFinancieras().then((e) => { setEntidades(e); setEntidadId(e[0] ? String(e[0].id) : ""); }).catch(notify.error); }, []);
  useEffect(() => { if (!entidadId) return; Promise.all([listarCuentasFinancieras(entidadId), listarBolsillos(entidadId)]).then(([c, b]) => { setCuentas(c.filter((x) => x.estado === "activa")); setBolsillos(b.filter((x) => x.estado === "activa")); }).catch(notify.error); }, [entidadId]);
  const enviar = async (tipo, form) => { try { const data = { ...form, cuenta_financiera_id: Number(form.cuenta_financiera_id), bolsillo_id: Number(form.bolsillo_id), importe_minor: Math.round(Number(form.importe) * 100) }; delete data.importe; if (tipo === "aporte") await registrarAporteSocio(entidadId, data, clave()); else await registrarPrestamoRecibido(entidadId, data, clave()); notify.success("Movimiento registrado"); } catch (e) { notify.error(e); } };
  const campos = (form, setForm, titulo, onGuardar) => <Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3 }}><Typography variant="h6" sx={{ mb: 2 }}>{titulo}</Typography><Stack spacing={2}><TextField label="Fecha" type="date" InputLabelProps={{ shrink: true }} value={form.fecha} onChange={(e) => setForm({ ...form, fecha: e.target.value })} /><TextField label="Importe (S/)" type="number" value={form.importe} onChange={(e) => setForm({ ...form, importe: e.target.value })} /><TextField select label="Cuenta receptora" value={form.cuenta_financiera_id} onChange={(e) => setForm({ ...form, cuenta_financiera_id: e.target.value })}>{cuentas.map((c) => <MenuItem key={c.id} value={c.id}>{c.nombre}</MenuItem>)}</TextField><TextField select label="Bolsillo destino" value={form.bolsillo_id} onChange={(e) => setForm({ ...form, bolsillo_id: e.target.value })}>{bolsillos.map((b) => <MenuItem key={b.id} value={b.id}>{b.nombre}</MenuItem>)}</TextField><TextField label="Descripción" value={form.descripcion} onChange={(e) => setForm({ ...form, descripcion: e.target.value })} /><Button variant="contained" onClick={onGuardar}>Registrar</Button></Stack></Paper>;
  return <Box><PageHeader title="Aportes y préstamos" subtitle="Entradas no operativas: no generan utilidad ni se mezclan con ventas." /><TextField select label="Entidad" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: 280, mb: 3 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField><Grid container spacing={2.5}><Grid item xs={12} md={6}>{campos(aporte, setAporte, "Aporte de socio", () => enviar("aporte", aporte))}</Grid><Grid item xs={12} md={6}>{campos(prestamo, setPrestamo, "Préstamo recibido", () => enviar("prestamo", prestamo))}</Grid></Grid></Box>;
}
