import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Divider, Grid, LinearProgress, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import PageHeader from "../components/PageHeader";
import EmptyState from "../components/EmptyState";
import { fechaHoyISO, formatoMoneda, formatoNumero } from "../utils/format";
import { actualizarObjetivoNegocio, cambiarEstadoObjetivoNegocio, crearObjetivoNegocio, dashboardObjetivosNegocio, listarEntidadesFinancieras, opcionesObjetivosNegocio, simuladorObjetivoNegocio } from "../api/endpoints";

const hoy = fechaHoyISO();
const vacio = { nombre: "", tipo: "facturacion", valor_objetivo: "", fecha_inicio: hoy, fecha_fin: "", observaciones: "", entidad_id: "", producto_id: "", vendedor_id: "", canal_venta: "" };
const etiquetas = { facturacion: "Facturación", unidades_vendidas: "Unidades vendidas", utilidad_bruta: "Utilidad bruta" };
const tono = { "En camino": "info", Adelantado: "success", "En riesgo": "warning", Cumplido: "success" };
const mostrar = (o, n) => o.tipo === "unidades_vendidas" ? `${formatoNumero(n, 0)} unid.` : formatoMoneda(n);

function Tendencia({ datos }) {
  const puntos = useMemo(() => { const valores = datos.map((x) => Number(x.ventas)); const max = Math.max(...valores, 1); return valores.map((v, i) => `${(i / Math.max(valores.length - 1, 1)) * 100},${92 - (v / max) * 76}`).join(" "); }, [datos]);
  if (!datos.length) return <Typography color="text.secondary">Aún no hay ventas recientes para mostrar una tendencia.</Typography>;
  return <Box><svg viewBox="0 0 100 100" width="100%" height="170" role="img" aria-label="Tendencia de ventas de los últimos 30 días" preserveAspectRatio="none"><line x1="0" y1="92" x2="100" y2="92" stroke="currentColor" opacity=".2" /><polyline fill="none" stroke="currentColor" strokeWidth="2" points={puntos} vectorEffect="non-scaling-stroke" /></svg><Stack direction="row" justifyContent="space-between"><Typography variant="caption">Hace 30 días</Typography><Typography variant="caption">Hoy</Typography></Stack></Box>;
}

export default function ObjetivosNegocioPage() {
  const [tablero, setTablero] = useState({ objetivos: [], resumen: {}, tendencia: [] }), [form, setForm] = useState(vacio), [editando, setEditando] = useState(null), [error, setError] = useState(""), [cargando, setCargando] = useState(true), [opciones, setOpciones] = useState({ productos: [], vendedores: [], canales: [] }), [entidades, setEntidades] = useState([]), [simId, setSimId] = useState(""), [simValor, setSimValor] = useState(""), [simulacion, setSimulacion] = useState(null);
  const cargar = async () => { setCargando(true); try { setTablero(await dashboardObjetivosNegocio()); } catch (e) { setError(e.message); } finally { setCargando(false); } };
  useEffect(() => { cargar(); opcionesObjetivosNegocio().then(setOpciones).catch((e) => setError(e.message)); listarEntidadesFinancieras().then(setEntidades).catch(() => {}); }, []);
  const guardar = async () => { try { const data = { ...form, valor_objetivo: Number(form.valor_objetivo) }; editando ? await actualizarObjetivoNegocio(editando, data) : await crearObjetivoNegocio(data); setForm(vacio); setEditando(null); await cargar(); } catch (e) { setError(e.message); } };
  const editar = (o) => { setEditando(o.id); setForm({ ...o, valor_objetivo: String(o.valor_objetivo), entidad_id: o.entidad_id || "", producto_id: o.producto_id || "", vendedor_id: o.vendedor_id || "", canal_venta: o.canal_venta || "" }); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); };
  const abrirSimulador = async (o) => { setSimId(String(o.id)); setSimValor(String(o.valor_objetivo)); try { setSimulacion(await simuladorObjetivoNegocio(o.id, o.valor_objetivo)); } catch (e) { setError(e.message); } };
  const recalcular = async (valor = simValor) => { if (!simId || Number(valor) <= 0) return; setSimValor(valor); try { setSimulacion(await simuladorObjetivoNegocio(simId, Number(valor))); } catch (e) { setError(e.message); } };
  const objetivoSim = tablero.objetivos.find((o) => String(o.id) === String(simId)); const r = tablero.resumen;
  return <Box><PageHeader title="Objetivos del negocio" subtitle="Un vistazo claro a lo que avanza, lo que necesita atención y cómo impactaría una nueva meta." />
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Grid container spacing={2} sx={{ mb: 3 }}>{[["Objetivos activos", r.activos || 0, "info"], ["Cumplidos", r.cumplidos || 0, "success"], ["En riesgo", r.en_riesgo || 0, "warning"], ["Próximos a vencer", r.proximos_a_vencer || 0, "error"]].map(([t, v, c]) => <Grid item xs={6} md={3} key={t}><Paper variant="outlined" sx={{ p: 2 }}><Typography variant="caption" color="text.secondary">{t}</Typography><Typography variant="h4" color={`${c}.main`}>{v}</Typography></Paper></Grid>)}</Grid>
    <Grid container spacing={2} sx={{ mb: 3 }}><Grid item xs={12} lg={7}><Paper variant="outlined" sx={{ p: 2.5, height: "100%" }}><Typography variant="h6">Tendencia de ventas</Typography><Typography variant="body2" color="text.secondary">Ventas registradas en los últimos 30 días.</Typography><Tendencia datos={tablero.tendencia} /></Paper></Grid><Grid item xs={12} lg={5}><Paper variant="outlined" sx={{ p: 2.5, height: "100%" }}><Typography variant="h6">Progreso general</Typography><Typography variant="body2" color="text.secondary">Promedio de los objetivos activos.</Typography><Typography variant="h3" sx={{ my: 2 }}>{formatoNumero(r.progreso_general || 0, 1)}%</Typography><LinearProgress variant="determinate" value={Math.min(100, r.progreso_general || 0)} sx={{ height: 12, borderRadius: 8 }} /><Divider sx={{ my: 2 }} /><Typography variant="caption" color="text.secondary">Cierre proyectado de objetivos activos</Typography><Typography variant="h5">{formatoMoneda(r.proyeccion_cierre || 0)}</Typography></Paper></Grid></Grid>
    <Paper variant="outlined" sx={{ p: 2.5, mb: 3 }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={1}><Box><Typography variant="h6">Simulador de objetivo</Typography><Typography variant="body2" color="text.secondary">Cambia el número y revisa al instante el esfuerzo y el impacto estimado. No mueve dinero.</Typography></Box><TextField select size="small" label="Objetivo" value={simId} onChange={(e) => { const o = tablero.objetivos.find((x) => String(x.id) === e.target.value); if (o) abrirSimulador(o); }} sx={{ minWidth: 240 }}><MenuItem value="">Selecciona un objetivo</MenuItem>{tablero.objetivos.map((o) => <MenuItem key={o.id} value={o.id}>{o.nombre}</MenuItem>)}</TextField></Stack>{objetivoSim && <Grid container spacing={2} sx={{ mt: .5 }}><Grid item xs={12} md={4}><TextField fullWidth type="number" label={objetivoSim.tipo === "unidades_vendidas" ? "Nuevo objetivo (unidades)" : "Nuevo objetivo (S/)"} value={simValor} onChange={(e) => recalcular(e.target.value)} /></Grid>{simulacion && <><Grid item xs={6} md={2}><Typography variant="caption">Ventas necesarias</Typography><Typography fontWeight={700}>{formatoMoneda(simulacion.ventas_necesarias)}</Typography></Grid><Grid item xs={6} md={2}><Typography variant="caption">Unidades necesarias</Typography><Typography fontWeight={700}>{formatoNumero(simulacion.unidades_necesarias, 0)}</Typography></Grid><Grid item xs={6} md={2}><Typography variant="caption">Tiempo estimado</Typography><Typography fontWeight={700}>{simulacion.tiempo_estimado_dias == null ? "Sin ritmo" : `${formatoNumero(simulacion.tiempo_estimado_dias, 1)} días`}</Typography></Grid><Grid item xs={6} md={2}><Typography variant="caption">Impacto financiero</Typography><Typography fontWeight={700}>{simulacion.impacto_financiero.disponible ? formatoMoneda(simulacion.impacto_financiero.importe_proyectado_minor / 100) : "No disponible"}</Typography></Grid><Grid item xs={12}>{simulacion.impacto_financiero.disponible ? <Stack direction="row" flexWrap="wrap" gap={1}>{[["Recuperación de costo", simulacion.impacto_financiero.recuperacion_costo_minor], ...simulacion.impacto_financiero.distribucion.map((x) => [x.nombre, x.importe_minor])].map(([n, v]) => <Chip key={n} label={`${n}: ${formatoMoneda(v / 100)}`} />)}</Stack> : <Alert severity="info">{simulacion.impacto_financiero.mensaje}</Alert>}</Grid></>}</Grid>}</Paper>
    <Typography variant="h6" sx={{ mb: 1 }}>Objetivos por producto, vendedor y canal</Typography>{cargando ? <Typography>Actualizando tablero…</Typography> : !tablero.objetivos.length ? <EmptyState title="Todavía no tienes objetivos" subtitle="Crea el primero para ver tu tablero ejecutivo." /> : <Grid container spacing={2}>{tablero.objetivos.map((o) => <Grid item xs={12} md={6} xl={4} key={o.id}><Paper variant="outlined" sx={{ p: 2.25, height: "100%" }}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h6">{o.nombre}</Typography><Typography variant="body2" color="text.secondary">{etiquetas[o.tipo]} · hasta {o.fecha_fin}</Typography></Box><Chip label={o.estado_visual} color={tono[o.estado_visual] || "default"} size="small" /></Stack><Box sx={{ mt: 2 }}><Stack direction="row" justifyContent="space-between"><Typography variant="body2">Avance</Typography><Typography fontWeight={700}>{formatoNumero(o.porcentaje_cumplimiento, 1)}%</Typography></Stack><LinearProgress variant="determinate" value={Math.min(100, o.porcentaje_cumplimiento)} sx={{ height: 9, borderRadius: 9, my: .75 }} /><Typography variant="body2">{mostrar(o, o.avance_actual)} de {mostrar(o, o.valor_objetivo)}</Typography></Box><Grid container spacing={1} sx={{ my: 1.5 }}><Grid item xs={6}><Typography variant="caption">Cierre estimado</Typography><Typography fontWeight={600}>{mostrar(o, o.proyeccion_cierre)}</Typography></Grid><Grid item xs={6}><Typography variant="caption">Falta</Typography><Typography fontWeight={600}>{mostrar(o, o.valor_faltante)}</Typography></Grid><Grid item xs={6}><Typography variant="caption">Ritmo</Typography><Typography fontWeight={600}>{mostrar(o, o.ritmo_diario)} / día</Typography></Grid><Grid item xs={6}><Typography variant="caption">Fecha prevista</Typography><Typography fontWeight={600}>{o.fecha_estimada_cumplimiento || "Sin estimación"}</Typography></Grid></Grid><Stack direction="row" spacing={1}><Button size="small" onClick={() => abrirSimulador(o)}>Simular</Button><Button size="small" onClick={() => editar(o)}>Editar</Button>{o.estado === "activo" && <Button size="small" onClick={async () => { await cambiarEstadoObjetivoNegocio(o.id, "cancelado"); cargar(); }}>Cancelar</Button>}</Stack></Paper></Grid>)}</Grid>}
    <Paper variant="outlined" sx={{ p: 2.5, mt: 3 }}><Typography variant="h6" sx={{ mb: 2 }}>{editando ? "Editar objetivo" : "Crear objetivo"}</Typography><Grid container spacing={2}><Grid item xs={12} md={4}><TextField fullWidth label="Nombre" value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /></Grid><Grid item xs={12} sm={6} md={2}><TextField select fullWidth label="Tipo" value={form.tipo} onChange={(e) => setForm({ ...form, tipo: e.target.value })}>{Object.entries(etiquetas).map(([k, v]) => <MenuItem key={k} value={k}>{v}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6} md={2}><TextField fullWidth type="number" label="Objetivo" value={form.valor_objetivo} onChange={(e) => setForm({ ...form, valor_objetivo: e.target.value })} /></Grid><Grid item xs={6} md={2}><TextField fullWidth type="date" label="Inicio" InputLabelProps={{ shrink: true }} value={form.fecha_inicio} onChange={(e) => setForm({ ...form, fecha_inicio: e.target.value })} /></Grid><Grid item xs={6} md={2}><TextField fullWidth type="date" label="Fin" InputLabelProps={{ shrink: true }} value={form.fecha_fin} onChange={(e) => setForm({ ...form, fecha_fin: e.target.value })} /></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth label="Entidad para simulación" value={form.entidad_id} onChange={(e) => setForm({ ...form, entidad_id: e.target.value })}><MenuItem value="">Sin seleccionar</MenuItem>{entidades.map((x) => <MenuItem key={x.id} value={x.id}>{x.nombre}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth label="Producto" value={form.producto_id} onChange={(e) => setForm({ ...form, producto_id: e.target.value })}><MenuItem value="">Todos</MenuItem>{opciones.productos.map((x) => <MenuItem key={x.id} value={x.id}>{x.nombre}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth label="Vendedor" value={form.vendedor_id} onChange={(e) => setForm({ ...form, vendedor_id: e.target.value })}><MenuItem value="">Todo el equipo</MenuItem>{opciones.vendedores.map((x) => <MenuItem key={x.id} value={x.id}>{x.nombre}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6} md={3}><TextField select fullWidth label="Canal" value={form.canal_venta} onChange={(e) => setForm({ ...form, canal_venta: e.target.value })}><MenuItem value="">Todos</MenuItem>{opciones.canales.map((x) => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField></Grid><Grid item xs={12}><TextField fullWidth multiline minRows={2} label="Observaciones" value={form.observaciones || ""} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Grid><Grid item xs={12}><Button variant="contained" onClick={guardar}>{editando ? "Guardar cambios" : "Crear objetivo"}</Button></Grid></Grid></Paper>
  </Box>;
}
