import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Checkbox, FormControlLabel, Grid, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import PageHeader from "../components/PageHeader";
import DataTable from "../components/DataTable";
import StatusChip from "../components/StatusChip";
import { useNotify } from "../hooks/useNotify";
import { formatoMoneda } from "../utils/format";
import {
  activarPoliticaFinanciera, aplicarPlantillaFinanciera, crearPoliticaFinanciera, crearVersionPoliticaFinanciera, listarBolsillos,
  listarEntidadesFinancieras, listarPlantillasFinancieras, listarPoliticasFinancieras, obtenerPoliticaFinanciera, simularPoliticaFinanciera, listarMetasFinancieras,
} from "../api/endpoints";

const reglaNueva = (bolsilloId = "") => ({ nombre: "Utilidad", bolsillo_id: bolsilloId, porcentaje: "0", accion: "aplicar", campo: "", operador: "igual", valor: "", bolsillo_destino_id: "" });

export default function PoliticasFinancierasPage() {
  const notify = useNotify();
  const [entidades, setEntidades] = useState([]); const [entidadId, setEntidadId] = useState("");
  const [bolsillos, setBolsillos] = useState([]); const [politicas, setPoliticas] = useState([]); const [plantillas, setPlantillas] = useState([]); const [metas, setMetas] = useState([]);
  const [form, setForm] = useState({ nombre: "Ventas DL8", recuperaCosto: true, bolsilloCostoId: "", reglas: [] });
  const [simulacion, setSimulacion] = useState(null); const [importe, setImporte] = useState("100"); const [loading, setLoading] = useState(true); const [editandoId, setEditandoId] = useState(null);
  const entidad = useMemo(() => entidades.find((x) => String(x.id) === String(entidadId)), [entidades, entidadId]);
  const puedeEditar = entidad?.rol_financiero === "finanzas_admin";
  const cargar = async (id = entidadId) => {
    if (!id) return; setLoading(true);
    try { const [b, p, m] = await Promise.all([listarBolsillos(id), listarPoliticasFinancieras(id), listarMetasFinancieras(id)]); setBolsillos(b.filter((x) => x.estado === "activa" && x.tipo !== "sin_asignar")); setPoliticas(p); setMetas(m.filter((x) => x.estado === "activa")); }
    catch (e) { notify.error(e); } finally { setLoading(false); }
  };
  useEffect(() => { Promise.all([listarEntidadesFinancieras(), listarPlantillasFinancieras()]).then(([e, t]) => { setEntidades(e); setPlantillas(t); setEntidadId(e[0] ? String(e[0].id) : ""); }).catch(notify.error); }, []);
  useEffect(() => { cargar(); }, [entidadId]);
  useEffect(() => { if (bolsillos.length && !form.reglas.length) setForm((f) => ({ ...f, bolsilloCostoId: f.bolsilloCostoId || String(bolsillos[0].id), reglas: [reglaNueva(String(bolsillos[0].id))] })); }, [bolsillos]);
  const actualizarRegla = (indice, cambios) => setForm((f) => ({ ...f, reglas: f.reglas.map((r, i) => i === indice ? { ...r, ...cambios } : r) }));
  const crear = async () => {
    try {
      const payload = { nombre: form.nombre, evento_tipo: "cobro_venta", recupera_costo: form.recuperaCosto, bolsillo_costo_id: form.recuperaCosto ? Number(form.bolsilloCostoId) : null, reglas: form.reglas.map((r) => ({ nombre: r.nombre, bolsillo_id: Number(r.bolsillo_id), meta_id: r.meta_id ? Number(r.meta_id) : null, bolsillo_destino_id: r.bolsillo_destino_id ? Number(r.bolsillo_destino_id) : null, accion: r.accion || "aplicar", condicion: r.campo ? { [r.campo]: r.operador === "minimo" ? Number(r.valor) * 100 : r.valor } : {}, base: "ingreso", tipo: "porcentaje", valor_minor: Math.round(Number(r.porcentaje) * 100) })) };
      const politica = editandoId ? await crearVersionPoliticaFinanciera(entidadId, editandoId, payload) : await crearPoliticaFinanciera(entidadId, payload);
      setSimulacion({ ...(await simularPoliticaFinanciera(entidadId, politica.id, Math.round(Number(importe) * 100))), politica_id: politica.id }); setEditandoId(null); await cargar(); notify.success(editandoId ? "Nueva versión guardada como borrador" : "Política guardada como borrador");
    } catch (e) { notify.error(e); }
  };
  const aplicarPlantilla = async (codigo) => { try { await aplicarPlantillaFinanciera(entidadId, codigo); await cargar(); notify.success("Plantilla creada como borrador"); } catch (e) { notify.error(e); } };
  const simular = async (p) => { try { setSimulacion({ ...(await simularPoliticaFinanciera(entidadId, p.id, Math.round(Number(importe) * 100))), politica_id: p.id }); } catch (e) { notify.error(e); } };
  const activar = async (id) => { try { await activarPoliticaFinanciera(entidadId, id, true); await cargar(); notify.success("Política activada"); } catch (e) { notify.error(e); } };
  const editar = async (id) => { try { const p = await obtenerPoliticaFinanciera(entidadId, id); setForm({ nombre: p.nombre, recuperaCosto: Boolean(p.recupera_costo), bolsilloCostoId: String(p.bolsillo_costo_id || ""), reglas: p.reglas.map((r) => ({ nombre: r.nombre, bolsillo_id: String(r.bolsillo_id), meta_id: String(r.meta_id || ""), porcentaje: String(r.valor_minor / 100) })) }); setEditandoId(id); window.scrollTo({ top: 0, behavior: "smooth" }); } catch (e) { notify.error(e); } };
  return <Box><PageHeader title="Políticas financieras" subtitle="Define cómo el ERP reserva el dinero recibido, antes de considerarlo disponible." />
    <TextField select label="Entidad" value={entidadId} onChange={(e) => setEntidadId(e.target.value)} sx={{ minWidth: 280, mb: 2 }}>{entidades.map((e) => <MenuItem key={e.id} value={e.id}>{e.nombre}</MenuItem>)}</TextField>
    {!entidad ? <Alert severity="info">No tienes una entidad financiera configurada.</Alert> : <Grid container spacing={2.5}><Grid item xs={12} lg={7}><Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3 }}><Typography variant="h6">Plantillas iniciales</Typography><Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>Crean bolsillos y una política en borrador para que puedas revisarla antes de activarla.</Typography><Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap>{plantillas.map((p) => <Button key={p.codigo} variant="outlined" disabled={!puedeEditar} onClick={() => aplicarPlantilla(p.codigo)}>{p.nombre}</Button>)}</Stack></Paper>
      <Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3, mt: 2.5 }}><Typography variant="h6" sx={{ mb: 2 }}>{editandoId ? "Editar: se creará una nueva versión" : "Asistente de política"}</Typography><Stack spacing={2}><TextField label="Nombre" value={form.nombre} onChange={(e) => setForm((f) => ({ ...f, nombre: e.target.value }))} /><FormControlLabel control={<Checkbox checked={form.recuperaCosto} onChange={(e) => setForm((f) => ({ ...f, recuperaCosto: e.target.checked }))} />} label="Recuperar costo real antes de distribuir utilidad" />{form.recuperaCosto && <TextField select label="Bolsillo para recuperar costo" value={form.bolsilloCostoId} onChange={(e) => setForm((f) => ({ ...f, bolsilloCostoId: e.target.value }))}>{bolsillos.map((b) => <MenuItem key={b.id} value={b.id}>{b.nombre}</MenuItem>)}</TextField>}<Typography variant="subtitle2">Distribución de la utilidad restante</Typography>{form.reglas.map((r, i) => <Stack key={i} direction={{ xs: "column", sm: "row" }} spacing={1}><TextField label="Destino" value={r.nombre} onChange={(e) => actualizarRegla(i, { nombre: e.target.value })} /><TextField select label="Bolsillo" value={r.bolsillo_id} onChange={(e) => actualizarRegla(i, { bolsillo_id: e.target.value })} sx={{ minWidth: 180 }}>{bolsillos.map((b) => <MenuItem key={b.id} value={b.id}>{b.nombre}</MenuItem>)}</TextField><TextField label="%" type="number" value={r.porcentaje} onChange={(e) => actualizarRegla(i, { porcentaje: e.target.value })} inputProps={{ min: 0, max: 100 }} /><Button color="error" onClick={() => setForm((f) => ({ ...f, reglas: f.reglas.filter((_, n) => n !== i) }))}>Quitar</Button></Stack>)}<Button onClick={() => setForm((f) => ({ ...f, reglas: [...f.reglas, reglaNueva(String(bolsillos[0]?.id || ""))] }))}>Agregar destino</Button><TextField label="Importe de simulación (S/)" type="number" value={importe} onChange={(e) => setImporte(e.target.value)} /><Button variant="contained" disabled={!puedeEditar} onClick={crear}>{editandoId ? "Guardar nueva versión y simular" : "Guardar y simular"}</Button></Stack></Paper></Grid>
      <Grid item xs={12} lg={5}><Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3 }}><Typography variant="h6" sx={{ mb: 1 }}>Políticas creadas</Typography><DataTable loading={loading} searchable={false} rows={politicas} rowsPerPageOptions={[5, 10]} columns={[{ field: "nombre", headerName: "Nombre", minWidth: 150 }, { field: "version", headerName: "Versión" }, { field: "estado", headerName: "Estado", renderCell: (r) => <StatusChip label={r.estado} tone={r.estado === "activa" ? "success" : "default"} /> }, { field: "acciones", headerName: "", sortable: false, renderCell: (r) => <Stack direction="row"><Button size="small" onClick={() => simular(r)}>Simular</Button><Button size="small" onClick={() => editar(r.id)}>Editar</Button><Button size="small" disabled={!puedeEditar || (r.estado === "activa" && r.es_predeterminada)} onClick={() => activar(r.id)}>Activar</Button></Stack> }]} /></Paper>{simulacion && <Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3, mt: 2.5 }}><Typography variant="h6">Simulación</Typography>{simulacion.costo_recuperado_minor > 0 && <Typography>Costo recuperado: {formatoMoneda(simulacion.costo_recuperado_minor / 100)}</Typography>}{simulacion.detalles.map((d) => <Typography key={d.regla_id}>{d.nombre}: {formatoMoneda(d.importe_minor / 100)}</Typography>)}<Typography sx={{ mt: 1 }}>Disponible sin asignar: {formatoMoneda(simulacion.disponible_minor / 100)}</Typography><Button sx={{ mt: 2 }} variant="contained" onClick={() => activar(simulacion.politica_id)}>Activar esta política</Button></Paper>}</Grid></Grid>}
    <Paper variant="outlined" sx={{ p: 2, borderRadius: 3, mt: 2 }}><Typography variant="subtitle2">Condiciones y acciones por regla</Typography>{form.reglas.map((r, i) => <Stack key={`cond-${i}`} direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ mt: 1 }}><Typography sx={{ minWidth: 110 }}>{r.nombre}</Typography><TextField select size="small" label="Campo" value={r.campo || ""} onChange={(e) => actualizarRegla(i, { campo: e.target.value })}><MenuItem value="">Sin condición</MenuItem><MenuItem value="canal">Canal</MenuItem><MenuItem value="monto_min_minor">Monto mínimo</MenuItem><MenuItem value="margen_min_minor">Margen mínimo</MenuItem><MenuItem value="periodo">Período</MenuItem><MenuItem value="meta_estado">Estado meta</MenuItem></TextField><TextField select size="small" label="Operador" value={r.operador || "igual"} onChange={(e) => actualizarRegla(i, { operador: e.target.value })}><MenuItem value="igual">Igual a</MenuItem><MenuItem value="minimo">Mayor o igual</MenuItem></TextField><TextField size="small" label="Valor" value={r.valor || ""} onChange={(e) => actualizarRegla(i, { valor: e.target.value })} /><TextField select size="small" label="Acción" value={r.accion || "aplicar"} onChange={(e) => actualizarRegla(i, { accion: e.target.value })}><MenuItem value="aplicar">Aplicar</MenuItem><MenuItem value="omitir">Omitir</MenuItem><MenuItem value="resto">Enviar resto</MenuItem></TextField></Stack>)}</Paper>
  </Box>;
}
