const {db}=require('../../db');
const cat=require('./catalogos');
const {hashCanonico}=require('./idempotencia');
const err=(message,status=400)=>Object.assign(new Error(message),{status});
const saldo=(cuentaId,bolsilloId)=>db.prepare(`SELECT COALESCE((SELECT SUM(importe_minor) FROM fin_movimientos_tesoreria WHERE cuenta_financiera_id=?),0) tes,COALESCE((SELECT SUM(CASE WHEN cuenta_destino_id=? AND bolsillo_destino_id=? THEN importe_minor ELSE 0 END)-SUM(CASE WHEN cuenta_origen_id=? AND bolsillo_origen_id=? THEN importe_minor ELSE 0 END) FROM fin_asignaciones_bolsillo),0) bol`).get(cuentaId,cuentaId,bolsilloId,cuentaId,bolsilloId);
function periodo(entidadId,fecha){const [anio,mes]=fecha.slice(0,7).split('-').map(Number);const row=db.prepare('SELECT * FROM fin_periodos WHERE entidad_id=? AND anio=? AND mes=?').get(entidadId,anio,mes);if(!row||row.estado!=='abierto')throw err('El período financiero no está abierto',409);return row}
const ejecutar=db.transaction(({entidadId,tipo,fecha,descripcion,usuarioId,clave,payload,lineas=[],asigs=[],reversionDeId=null})=>{
  cat.exigirAcceso(entidadId,usuarioId,['finanzas_admin','finanzas_operador','finanzas_personal_propietario']);
  const payloadHash=hashCanonico(payload),previo=db.prepare('SELECT * FROM fin_claves_idempotencia WHERE entidad_id=? AND clave=?').get(entidadId,clave);
  if(previo){if(previo.hash_payload!==payloadHash)throw err('La clave de idempotencia se usó con otro payload',409);return{id:previo.evento_id,repetido:true}}
  const p=periodo(entidadId,fecha),debe=lineas.reduce((n,l)=>n+l.debe_minor,0),haber=lineas.reduce((n,l)=>n+l.haber_minor,0);
  if(tipo!=='reasignacion_bolsillo'&&debe!==haber)throw err('El asiento no está balanceado');
  const eventoId=Number(db.prepare('INSERT INTO fin_eventos_financieros(entidad_id,tipo,fecha,descripcion,reversion_de_id,creado_por)VALUES(?,?,?,?,?,?)').run(entidadId,tipo,fecha,descripcion,reversionDeId,usuarioId).lastInsertRowid);
  db.prepare('INSERT INTO fin_eventos_por_entidad(evento_id,entidad_id)VALUES(?,?)').run(eventoId,entidadId);
  if(lineas.length){const asientoId=Number(db.prepare('INSERT INTO fin_asientos_contables(evento_id,entidad_id,periodo_id,fecha,glosa)VALUES(?,?,?,?,?)').run(eventoId,entidadId,p.id,fecha,descripcion).lastInsertRowid);for(const linea of lineas){const lineaId=Number(db.prepare('INSERT INTO fin_lineas_asiento(asiento_id,cuenta_contable_id,cuenta_financiera_id,debe_minor,haber_minor)VALUES(?,?,?,?,?)').run(asientoId,linea.cuenta_contable_id,linea.cuenta_financiera_id||null,linea.debe_minor,linea.haber_minor).lastInsertRowid);if(linea.cuenta_financiera_id)db.prepare('INSERT INTO fin_movimientos_tesoreria(evento_id,linea_asiento_id,cuenta_financiera_id,importe_minor)VALUES(?,?,?,?)').run(eventoId,lineaId,linea.cuenta_financiera_id,linea.debe_minor-linea.haber_minor)}}
  for(const asignacion of asigs){if(asignacion.cuenta_origen_id&&saldo(asignacion.cuenta_origen_id,asignacion.bolsillo_origen_id).bol<asignacion.importe_minor)throw err('Saldo de bolsillo insuficiente',409);db.prepare('INSERT INTO fin_asignaciones_bolsillo(evento_id,cuenta_origen_id,bolsillo_origen_id,cuenta_destino_id,bolsillo_destino_id,importe_minor)VALUES(?,?,?,?,?,?)').run(eventoId,asignacion.cuenta_origen_id||null,asignacion.bolsillo_origen_id||null,asignacion.cuenta_destino_id||null,asignacion.bolsillo_destino_id||null,asignacion.importe_minor)}
  db.prepare('INSERT INTO fin_claves_idempotencia(entidad_id,clave,hash_payload,evento_id)VALUES(?,?,?,?)').run(entidadId,clave,payloadHash,eventoId);return{id:eventoId,repetido:false};
});
const cuenta=(entidadId,id)=>{const row=db.prepare("SELECT * FROM fin_cuentas_financieras WHERE id=? AND entidad_id=? AND estado='activa'").get(id,entidadId);if(!row)throw err('Cuenta financiera no pertenece a la entidad',409);return row};
const bolsillo=(entidadId,id)=>{const row=db.prepare("SELECT * FROM fin_bolsillos WHERE id=? AND entidad_id=? AND estado='activa'").get(id,entidadId);if(!row)throw err('Bolsillo no pertenece a la entidad',409);return row};
const cmd=(entidadId,usuarioId,clave,payload)=>{if(!clave)throw err('Idempotency-Key es obligatorio');return ejecutar({entidadId,usuarioId,clave,payload,...payload})};
function inicial(e,u,k,p){const c=cuenta(e,p.cuenta_financiera_id),b=bolsillo(e,p.bolsillo_id),n=Number(p.importe_minor);if(!Number.isInteger(n)||n<=0)throw err('importe_minor inválido');const pc=db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo='3901'").get(e);return cmd(e,u,k,{tipo:'saldo_inicial',fecha:p.fecha,descripcion:p.descripcion||'Saldo inicial',lineas:[{cuenta_contable_id:c.cuenta_contable_id,cuenta_financiera_id:c.id,debe_minor:n,haber_minor:0},{cuenta_contable_id:pc.id,debe_minor:0,haber_minor:n}],asigs:[{cuenta_destino_id:c.id,bolsillo_destino_id:b.id,importe_minor:n}]})}
function transferencia(e,u,k,p){const o=cuenta(e,p.cuenta_origen_id),d=cuenta(e,p.cuenta_destino_id),bo=bolsillo(e,p.bolsillo_origen_id),bd=bolsillo(e,p.bolsillo_destino_id||p.bolsillo_origen_id),n=Number(p.importe_minor);if(o.id===d.id||!Number.isInteger(n)||n<=0)throw err('Transferencia inválida');return cmd(e,u,k,{tipo:'transferencia_interna',fecha:p.fecha,descripcion:p.descripcion||'Transferencia interna',lineas:[{cuenta_contable_id:d.cuenta_contable_id,cuenta_financiera_id:d.id,debe_minor:n,haber_minor:0},{cuenta_contable_id:o.cuenta_contable_id,cuenta_financiera_id:o.id,debe_minor:0,haber_minor:n}],asigs:[{cuenta_origen_id:o.id,bolsillo_origen_id:bo.id,cuenta_destino_id:d.id,bolsillo_destino_id:bd.id,importe_minor:n}]})}
function reasignar(e,u,k,p){const c=cuenta(e,p.cuenta_financiera_id),o=bolsillo(e,p.bolsillo_origen_id),d=bolsillo(e,p.bolsillo_destino_id),n=Number(p.importe_minor);if(o.id===d.id||!Number.isInteger(n)||n<=0)throw err('Reasignación inválida');return cmd(e,u,k,{tipo:'reasignacion_bolsillo',fecha:p.fecha,descripcion:p.descripcion||'Reasignación de bolsillo',lineas:[],asigs:[{cuenta_origen_id:c.id,bolsillo_origen_id:o.id,cuenta_destino_id:c.id,bolsillo_destino_id:d.id,importe_minor:n}]})}
function ingresoNoOperativo(e,u,k,p,tipo,codigo,descripcion){const c=cuenta(e,p.cuenta_financiera_id),b=bolsillo(e,p.bolsillo_id),n=Number(p.importe_minor),contra=db.prepare("SELECT id FROM fin_plan_cuentas WHERE entidad_id=? AND codigo=? AND estado='activa' AND permite_movimiento=1").get(e,codigo);if(!Number.isInteger(n)||n<=0)throw err('importe_minor inválido');if(!contra)throw err('La entidad no tiene la cuenta contable requerida',409);return cmd(e,u,k,{tipo,fecha:p.fecha,descripcion:p.descripcion||descripcion,lineas:[{cuenta_contable_id:c.cuenta_contable_id,cuenta_financiera_id:c.id,debe_minor:n,haber_minor:0},{cuenta_contable_id:contra.id,debe_minor:0,haber_minor:n}],asigs:[{cuenta_destino_id:c.id,bolsillo_destino_id:b.id,importe_minor:n}]})}
function aporteSocio(e,u,k,p){return ingresoNoOperativo(e,u,k,p,'aporte_socio','3101','Aporte de socio')}
function prestamoRecibido(e,u,k,p){return ingresoNoOperativo(e,u,k,p,'prestamo_recibido','2101','Préstamo recibido')}
function eventos(entidadId){return db.prepare(`SELECT ev.*,CASE WHEN EXISTS(SELECT 1 FROM fin_eventos_financieros r WHERE r.reversion_de_id=ev.id) THEN 'revertido' ELSE 'confirmado' END estado FROM fin_eventos_financieros ev WHERE ev.entidad_id=? ORDER BY ev.id DESC`).all(entidadId)}
function saldos(e){return{tesoreria:db.prepare('SELECT c.id,c.codigo,c.nombre,c.tipo,c.proveedor,COALESCE(SUM(m.importe_minor),0) saldo_minor FROM fin_cuentas_financieras c LEFT JOIN fin_movimientos_tesoreria m ON m.cuenta_financiera_id=c.id WHERE c.entidad_id=? GROUP BY c.id').all(e),bolsillos:db.prepare('SELECT b.id,b.nombre,b.tipo,COALESCE(SUM(CASE WHEN a.bolsillo_destino_id=b.id THEN a.importe_minor ELSE 0 END)-SUM(CASE WHEN a.bolsillo_origen_id=b.id THEN a.importe_minor ELSE 0 END),0) saldo_minor FROM fin_bolsillos b LEFT JOIN fin_asignaciones_bolsillo a ON b.id IN(a.bolsillo_origen_id,a.bolsillo_destino_id) WHERE b.entidad_id=? GROUP BY b.id').all(e)}}
function saldoCaja(e){return db.prepare("SELECT COALESCE(SUM(m.importe_minor),0) saldo_minor FROM fin_cuentas_financieras c LEFT JOIN fin_movimientos_tesoreria m ON m.cuenta_financiera_id=c.id WHERE c.entidad_id=? AND c.tipo='caja' AND c.estado='activa'").get(e)}
function saldoCuentaFinanciera(e,id){const c=db.prepare('SELECT id,codigo,nombre,tipo,proveedor,estado FROM fin_cuentas_financieras WHERE entidad_id=? AND id=?').get(e,id);if(!c)throw err('Cuenta financiera no encontrada',404);return{...c,saldo_minor:db.prepare('SELECT COALESCE(SUM(importe_minor),0) saldo_minor FROM fin_movimientos_tesoreria WHERE cuenta_financiera_id=?').get(c.id).saldo_minor}}
function utilidadPeriodoActual(e,fecha=new Date()){const p=db.prepare('SELECT id,anio,mes,estado FROM fin_periodos WHERE entidad_id=? AND anio=? AND mes=?').get(e,fecha.getFullYear(),fecha.getMonth()+1);if(!p)return{periodo:null,ingresos_minor:0,costos_minor:0,gastos_minor:0,utilidad_minor:0};const r=db.prepare("SELECT COALESCE(SUM(CASE WHEN pc.naturaleza='ingreso' THEN l.haber_minor-l.debe_minor ELSE 0 END),0) ingresos_minor,COALESCE(SUM(CASE WHEN pc.naturaleza='costo' THEN l.debe_minor-l.haber_minor ELSE 0 END),0) costos_minor,COALESCE(SUM(CASE WHEN pc.naturaleza='gasto' THEN l.debe_minor-l.haber_minor ELSE 0 END),0) gastos_minor FROM fin_lineas_asiento l JOIN fin_asientos_contables a ON a.id=l.asiento_id JOIN fin_plan_cuentas pc ON pc.id=l.cuenta_contable_id WHERE a.entidad_id=? AND a.periodo_id=?").get(e,p.id);return{periodo:{anio:p.anio,mes:p.mes,estado:p.estado},...r,utilidad_minor:r.ingresos_minor-r.costos_minor-r.gastos_minor}}
function dondeEstaDinero(e){const ubicaciones=saldos(e).tesoreria.map((c)=>({...c,saldo_fisico_minor:c.saldo_minor,asignado_minor:0,diferencia_minor:c.saldo_minor}));const bolsillos=saldos(e).bolsillos;const fisico=ubicaciones.reduce((n,x)=>n+x.saldo_fisico_minor,0),asignado=bolsillos.reduce((n,x)=>n+x.saldo_minor,0);const sin=bolsillos.filter((b)=>b.tipo==='sin_asignar').reduce((n,b)=>n+b.saldo_minor,0);return{ubicaciones,bolsillos,finalidades:[{nombre:'sin_asignar',saldo_minor:sin}],conciliacion:{saldo_fisico_minor:fisico,asignado_minor:asignado,diferencia_minor:fisico-asignado},alertas:sin>0?[{tipo:'sin_asignar',importe_minor:sin}]:[]}}
const revertir=db.transaction(({entidadId,eventoId,usuarioId,clave,permitirVinculado=false})=>{const original=db.prepare('SELECT * FROM fin_eventos_financieros WHERE id=? AND entidad_id=?').get(eventoId,entidadId);if(!original)throw err('Evento no encontrado',404);if(!permitirVinculado&&(db.prepare('SELECT 1 FROM fin_documentos_cxc WHERE evento_emision_id=?').get(eventoId)||db.prepare('SELECT 1 FROM fin_cobros WHERE evento_financiero_id=?').get(eventoId)||db.prepare('SELECT 1 FROM fin_documentos_cxp WHERE evento_emision_id=?').get(eventoId)||db.prepare('SELECT 1 FROM fin_pagos_cxp WHERE evento_financiero_id=?').get(eventoId)))throw err('El evento pertenece a un documento CxC/CxP y debe revertirse desde su flujo de dominio',409);if(db.prepare('SELECT 1 FROM fin_eventos_financieros WHERE reversion_de_id=?').get(eventoId))throw err('El evento ya fue revertido',409);const lineas=db.prepare('SELECT l.* FROM fin_lineas_asiento l JOIN fin_asientos_contables a ON a.id=l.asiento_id WHERE a.evento_id=?').all(eventoId).map(l=>({cuenta_contable_id:l.cuenta_contable_id,cuenta_financiera_id:l.cuenta_financiera_id,debe_minor:l.haber_minor,haber_minor:l.debe_minor}));const asigs=db.prepare('SELECT * FROM fin_asignaciones_bolsillo WHERE evento_id=?').all(eventoId).map(a=>({cuenta_origen_id:a.cuenta_destino_id,bolsillo_origen_id:a.bolsillo_destino_id,cuenta_destino_id:a.cuenta_origen_id,bolsillo_destino_id:a.bolsillo_origen_id,importe_minor:a.importe_minor}));return cmd(entidadId,usuarioId,clave,{tipo:'reversion',fecha:original.fecha,descripcion:`Reversión ${eventoId}`,lineas,asigs,reversionDeId:eventoId})});
module.exports={ejecutar,saldo,inicial,transferencia,reasignar,aporteSocio,prestamoRecibido,eventos,saldos,saldoCaja,saldoCuentaFinanciera,utilidadPeriodoActual,dondeEstaDinero,revertir};
